(()=>{
const $=id=>document.getElementById(id);
const num=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const fmt=(v,d=0,suffix='%')=>num(v)==null?'—':`${num(v).toFixed(d)}${suffix}`;
function prior(rows,key){const vals=(rows||[]).map(r=>num(r?.[key])).filter(v=>v!=null);return vals.length>1?vals[vals.length-2]:null}
function delta(cur,prev,threshold=1){if(cur==null||prev==null)return{symbol:'',word:'Current',cls:'state',detail:''};const d=cur-prev;if(Math.abs(d)<threshold)return{symbol:'→',word:'Stable',cls:'stable',detail:`from ${prev.toFixed(0)}%`};return d>0?{symbol:'↑',word:'Improving',cls:'improving',detail:`from ${prev.toFixed(0)}%`}:{symbol:'↓',word:'Deteriorating',cls:'deteriorating',detail:`from ${prev.toFixed(0)}%`}}
function partRead(v,kind){if(v==null)return'Unavailable';if(kind==='short')return v<20?'Washout':v<35?'Weak':v<50?'Soft':v>=70?'Broad':'Healthy';if(kind==='mid')return v<40?'Weak':v<50?'Mixed':v>=60?'Healthy':'Neutral';return v<40?'Weak':v<60?'Mixed':'Healthy'}
function trendRead(v){if(v==null)return'Unavailable';return v<0?'Below support':v<1?'Near support':'Above support'}
function stressRead(v){if(v==null)return'Unavailable';return v>=30?'High':v>=20?'Rising':v<15?'Very calm':'Low'}
function ensure(){const hero=document.querySelector('.premium-hero');if(!hero)return null;let sec=$('keyReadings');if(!sec){sec=document.createElement('section');sec.id='keyReadings';sec.className='key-readings';sec.innerHTML='<div class="key-readings-head"><span>KEY READINGS</span><small>The numbers driving today’s market read</small></div><div id="keyReadingsGrid" class="key-readings-grid"></div>';hero.after(sec)}return sec}
function healthDirections(h){const rows=h?.breadth||[],cells=document.querySelectorAll('#healthGrid .health-cell');if(!cells.length)return;const cur=rows[rows.length-1]||{},prev=rows[rows.length-2]||{};const b50=num(cur.above_50d),p50=num(prev.above_50d);const dir=delta(b50,p50,2);cells.forEach((c,i)=>{let tag=c.querySelector('.health-direction');if(!tag){tag=document.createElement('small');tag.className='health-direction';c.querySelector('.health-cell-head')?.appendChild(tag)}if(i===0)tag.textContent='→ CURRENT STRUCTURE';else if(i===1){tag.textContent=`${dir.symbol} ${dir.word.toUpperCase()}`;tag.className=`health-direction ${dir.cls}`}else if(i===2)tag.textContent='→ CURRENT STRESS'})}
function tacticalChecklist(d){const host=$('heroTactical');if(!host)return;let row=$('tacticalEvidenceMini');if(!row){row=document.createElement('div');row.id='tacticalEvidenceMini';row.className='tactical-evidence-mini';host.appendChild(row)}const b=d.breadth||{},b5=num(b.above_5d),rsi=num(b.rsi_below_30),trin=num(b.trin);const participation=b5==null?'Unavailable':b5<20?'Extreme':b5<35?'Weak':'Not extreme';const oversold=rsi==null?'Unavailable':rsi>=20?'Extreme':rsi>=10?'Building':'Not extreme';const pressure=trin==null?'Unavailable':trin>=1.3?'Heavy':trin<=.7?'Buying pressure':'Normal';row.innerHTML=`<span><b>Participation</b>${participation}</span><span><b>Oversold stocks</b>${oversold}</span><span><b>Selling pressure</b>${pressure}</span>`}
function render(d,h){ensure();const rows=h?.breadth||[],last=rows[rows.length-1]||{},p5=prior(rows,'above_5d'),p50=prior(rows,'above_50d'),p200=prior(rows,'above_200d');const b=d.breadth||{},b5=num(b.above_5d),b50=num(b.above_50d),b200=num(b.above_200d),v=num(d.vix?.value),s50=num(d.etfs?.SPY?.distance_ma50),q50=num(d.etfs?.QQQ?.distance_ma50);const d5=delta(b5,p5,3),d50=delta(b50,p50,2),d200=delta(b200,p200,1.5);const rowsOut=[
['One-week participation',fmt(b5),d5,partRead(b5,'short'),'MMFD-style breadth'],
['Intermediate participation',fmt(b50),d50,partRead(b50,'mid'),'Stocks above 50-day average'],
['Long-term participation',fmt(b200),d200,partRead(b200,'long'),'Stocks above 200-day average'],
['Fear level',v==null?'—':v.toFixed(1),{symbol:'',word:'Current',cls:'state',detail:''},stressRead(v),'VIX'],
['SPY intermediate trend',s50==null?'—':`${s50>=0?'+':''}${s50.toFixed(1)}%`,{symbol:'',word:'Current',cls:'state',detail:''},trendRead(s50),'vs 50-day average'],
['QQQ intermediate trend',q50==null?'—':`${q50>=0?'+':''}${q50.toFixed(1)}%`,{symbol:'',word:'Current',cls:'state',detail:''},trendRead(q50),'vs 50-day average']
];const grid=$('keyReadingsGrid');if(grid)grid.innerHTML=rowsOut.map(([name,value,dir,read,tech])=>`<article><div><span>${name}</span><small>${tech}</small></div><strong>${value}</strong><em class="${dir.cls}">${dir.symbol} ${dir.word}${dir.detail?` · ${dir.detail}`:''}</em><b>${read}</b></article>`).join('');healthDirections(h);tacticalChecklist(d)}
async function boot(){try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!dr.ok)return;const d=await dr.json(),h=hr.ok?await hr.json():{};[350,900,1700,3000].forEach(ms=>setTimeout(()=>render(d,h),ms))}catch(e){console.warn('Actionable summary:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(boot,1200));
})();
