(()=>{
const $=id=>document.getElementById(id);
const n=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const fmt=v=>n(v)==null?'—':Math.round(n(v));
function toneClass(t){return `agency-tone-${t}`}
function signal(label,value,copy,tone,metric){return `<article class="agency-signal ${toneClass(tone)}"><div class="agency-signal-top"><span>${label}</span><i></i></div><strong>${value}</strong><p>${copy}</p>${metric?`<small>${metric}</small>`:''}</article>`}
function trendRead(d){const b=n(d.breadth?.above_200d),s=n(d.etfs?.SPY?.distance_ma200),q=n(d.etfs?.QQQ?.distance_ma200);if([b,s,q].some(x=>x==null))return{value:'Data incomplete',copy:'Long-term trend evidence is not fully available.',tone:'neutral'};if(b<40||s<0||q<0)return{value:'Structural damage',copy:'Long-term support is breaking across price or participation.',tone:'bad'};if(b<55||s<2||q<2)return{value:'Under pressure',copy:'The primary trend is still alive, but its cushion is getting thinner.',tone:'warn'};return{value:'Trend intact',copy:'The long-term market structure remains supportive.',tone:'good'} }
function participationRead(d){const b5=n(d.breadth?.above_5d),b50=n(d.breadth?.above_50d);if(b5==null||b50==null)return{value:'Data incomplete',copy:'Participation data is not fully available.',tone:'neutral',metric:''};if(b5<15)return{value:'Washout',copy:'Selling is hitting nearly everything in the very short term.',tone:'bad',metric:`${fmt(b5)}% above 5-day · ${fmt(b50)}% above 50-day`};if(b5<30)return{value:'Broadly weak',copy:'Short-term selling is widespread, but intermediate participation is not yet structurally broken.',tone:'warn',metric:`${fmt(b5)}% above 5-day · ${fmt(b50)}% above 50-day`};if(b5<50||b50<45)return{value:'Softening',copy:'Participation has cooled enough to matter, but this is not broad damage.',tone:'warn',metric:`${fmt(b5)}% above 5-day · ${fmt(b50)}% above 50-day`};return{value:'Healthy',copy:'Most stocks are still participating across the important horizons.',tone:'good',metric:`${fmt(b5)}% above 5-day · ${fmt(b50)}% above 50-day`}}
function momentumRead(d){const s=d.etfs?.SPY||{},q=d.etfs?.QQQ||{},rs=[n(s.rsi14),n(q.rsi14)].filter(x=>x!=null),ws=[n(s.williams_r14),n(q.williams_r14)].filter(x=>x!=null);if(!rs.length&&!ws.length)return{value:'Data incomplete',copy:'Momentum data is not available.',tone:'neutral',metric:''};const r=rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:null,w=ws.length?ws.reduce((a,b)=>a+b,0)/ws.length:null;if((r!=null&&r<35)||(w!=null&&w<-80))return{value:'Oversold stretch',copy:'Short-term momentum is stretched enough to watch for stabilization, not enough to call a bottom.',tone:'warn',metric:`RSI ${r==null?'—':r.toFixed(0)} · Williams ${w==null?'—':w.toFixed(0)}`};if((r!=null&&r>70)||(w!=null&&w>-20))return{value:'Overbought stretch',copy:'Momentum is extended on the upside and vulnerable to a reset.',tone:'warn',metric:`RSI ${r==null?'—':r.toFixed(0)} · Williams ${w==null?'—':w.toFixed(0)}`};if(r!=null&&r<45)return{value:'Momentum soft',copy:'Momentum has weakened, but it is not yet at an exhaustion extreme.',tone:'warn',metric:`RSI ${r.toFixed(0)} · Williams ${w==null?'—':w.toFixed(0)}`};return{value:'Neutral momentum',copy:'Momentum is neither unusually stretched nor confirming a strong reversal setup.',tone:'good',metric:`RSI ${r==null?'—':r.toFixed(0)} · Williams ${w==null?'—':w.toFixed(0)}`}}
function turnRead(d){const c=d.breadth_cycle||{},state=String(c.state||''),dir=String(c.direction||''),p=n(c.percentile_63d);if(!state)return{value:'Not available',copy:'Turning-point pressure is not available.',tone:'neutral',metric:''};const low=p!=null&&p<=10;if(/recovery|stabil/i.test(state))return{value:'Turn developing',copy:'Breadth pressure is starting to improve. Price still needs to confirm.',tone:'good',metric:`Breadth momentum ${p==null?'—':p.toFixed(0)+'th pct'}`};if(/washout|approach/i.test(state)||low)return{value:'Near washout',copy:'Breadth pressure is near an extreme, but buyers have not confirmed a turn yet.',tone:'warn',metric:`${state} · ${p==null?'—':p.toFixed(0)+'th pct'}`};if(/deterior/i.test(dir))return{value:'Pressure building',copy:'Internal market pressure is still worsening rather than stabilizing.',tone:'warn',metric:`${state}`};return{value:state,copy:'No high-quality turning-point setup is confirmed yet.',tone:'neutral',metric:p==null?'':`${p.toFixed(0)}th percentile`}}
function paragraph(d,t,p,m,c){const b5=n(d.breadth?.above_5d),b50=n(d.breadth?.above_50d),b200=n(d.breadth?.above_200d),spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},s50=n(spy.distance_ma50),q50=n(qqq.distance_ma50);let out=[];
if(t.tone==='good')out.push(`The long-term market structure is still intact, with ${b200==null?'most':Math.round(b200)+'% of'} S&P 500 stocks holding above their 200-day trend and both SPY and QQQ still above long-term support.`);else out.push('The long-term structure is showing enough damage that short-term weakness deserves more respect than an ordinary dip.');
if(b5!=null&&b5<30)out.push(`Short-term participation has weakened sharply: only ${Math.round(b5)}% of S&P 500 stocks are above their 5-day average, while ${b50==null?'intermediate participation is still holding up better':Math.round(b50)+'% remain above the 50-day trend'}. That looks more like a broad short-term reset than a full structural breakdown.`);else out.push('Short-term participation has cooled, but selling is not broad enough to qualify as a true washout.');
if(m.value==='Oversold stretch')out.push('Momentum is becoming oversold enough to watch for exhaustion, but the dashboard is not treating that as a bottom until participation actually stabilizes.');else if(m.tone==='warn')out.push('Momentum is soft enough to matter, but it has not reached a convincing exhaustion extreme.');else out.push('Momentum is not unusually stretched, so there is no strong mean-reversion signal yet.');
if(c.value==='Near washout')out.push('Breadth momentum is approaching a historical washout zone, making the next improvement in participation more important than another weak day in price.');
const risk=(s50!=null&&s50<0)||(q50!=null&&q50<0)?'The view worsens materially if SPY and QQQ lose intermediate support while participation keeps deteriorating.':'The key confirmation would be participation stabilizing and turning higher; the key failure would be weakness spreading into the 50-day trend and then the long-term structure.';out.push(risk);return out.join(' ')}
function ensure(){const hero=document.querySelector('.premium-hero');if(!hero)return null;let wrap=$('agencyBrief');if(wrap)return wrap;wrap=document.createElement('div');wrap.id='agencyBrief';wrap.className='agency-brief';const thesis=hero.querySelector('.regime-thesis');if(thesis){thesis.id='agencyMarketBrief';thesis.classList.add('agency-market-brief')}const cond=$('condition');if(cond){cond.classList.add('agency-regime-tag')}const grid=document.createElement('div');grid.id='agencySignalGrid';grid.className='agency-signal-grid';(thesis||cond||hero.querySelector('.hero-grid>div'))?.after(grid);const watch=document.createElement('div');watch.id='agencyWatch';watch.className='agency-watch';grid.after(watch);hero.classList.add('agency-hero');return wrap}
function render(d){ensure();const t=trendRead(d),p=participationRead(d),m=momentumRead(d),c=turnRead(d);const brief=$('agencyMarketBrief')||$('summary');if(brief)brief.textContent=paragraph(d,t,p,m,c);const grid=$('agencySignalGrid');if(grid)grid.innerHTML=[signal('PRIMARY TREND',t.value,t.copy,t.tone,b200Metric(d)),signal('PARTICIPATION',p.value,p.copy,p.tone,p.metric),signal('MOMENTUM / STRETCH',m.value,m.copy,m.tone,m.metric),signal('TURNING-POINT PRESSURE',c.value,c.copy,c.tone,c.metric)].join('');const watch=$('agencyWatch');if(watch)watch.innerHTML='<span>WHAT CHANGES THE VIEW</span><strong>'+watchLine(d)+'</strong>';document.querySelectorAll('#dailyExperience,#retailSnapshot').forEach(el=>el.hidden=true)}
function b200Metric(d){const b=n(d.breadth?.above_200d),s=n(d.etfs?.SPY?.distance_ma200),q=n(d.etfs?.QQQ?.distance_ma200);return `${b==null?'—':Math.round(b)+'%'} above 200-day · SPY ${s==null?'—':(s>=0?'+':'')+s.toFixed(1)+'%'} · QQQ ${q==null?'—':(q>=0?'+':'')+q.toFixed(1)+'%'}`}
function watchLine(d){const b5=n(d.breadth?.above_5d),b50=n(d.breadth?.above_50d),s50=n(d.etfs?.SPY?.distance_ma50),q50=n(d.etfs?.QQQ?.distance_ma50);if((s50!=null&&s50<0)||(q50!=null&&q50<0))return 'A reclaim of intermediate support plus improving participation would repair the setup; continued deterioration would raise structural risk.';if(b5!=null&&b5<30)return `A rebound in 5-day participation from ${Math.round(b5)}% toward 40–50% would be the first useful sign that selling pressure is exhausting. A break below the 50-day trend would weaken the pullback thesis.`;if(b50!=null&&b50<45)return 'Watch whether 50-day participation stabilizes. Further deterioration while indexes hold near highs would create a more important divergence.';return 'The earliest warning would be participation narrowing while SPY or QQQ lose intermediate support.'}
async function boot(){try{const r=await fetch('data/market_context.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json();[100,450,1000,2200].forEach(ms=>setTimeout(()=>render(d),ms))}catch(e){console.warn('Agency hero:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();$('refresh')?.addEventListener('click',()=>setTimeout(boot,1400));
})();