(()=>{
const $=id=>document.getElementById(id);const num=v=>Number.isFinite(Number(v))?Number(v):null;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CT='America/Chicago',ET='America/New_York';let lastDaily=null,lastHist=null,lastLive=null;
function fmtTime(d,tz=CT){return new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'numeric',minute:'2-digit',hour12:true,timeZoneName:'short'}).format(d)}
function parts(d,tz){const a=new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);return Object.fromEntries(a.map(x=>[x.type,x.value]))}
function etSession(now=new Date()){const p=parts(now,ET),mins=Number(p.hour)*60+Number(p.minute),weekday=['Mon','Tue','Wed','Thu','Fri'].includes(p.weekday);if(!weekday)return{phase:'closed',label:'Markets closed',detail:'Weekend · most recent closing read remains official'};if(mins<570)return{phase:'pre',label:'Before the open',detail:'Morning Read is based on the previous confirmed close'};if(mins<960)return{phase:'open',label:'Market open',detail:'Official regime remains anchored to the previous close'};return{phase:'after',label:'After the close',detail:'Closing Read appears only after new closing data is confirmed'}}
function dateInTZ(d,tz){const p=parts(d,tz);return `${p.year}-${p.month}-${p.day}`}
function regimeOf(d){return typeof regime==='function'?regime(d):{name:'Market read',tone:'neutral',why:''}}
function approxHistState(m,b){if(!m)return'Mixed';const v=num(m.vix),b5=num(b?.above_5d),b50=num(b?.above_50d),b200=num(b?.above_200d);if(v>=30||b200<40)return'Risk-off / structural weakness';if(b5<25&&b200>=60)return'Washout developing';if(b50<40&&b200>=60)return'Trend deterioration';if((b5<45||false)&&b200>=60)return'Healthy pullback';if(b200>=60)return'Healthy uptrend';return'Mixed / transitional market'}
function regimeHistory(d,h){const bm=new Map((h?.breadth||[]).map(x=>[x.date,x]));return (h?.market||[]).map(m=>({date:m.date,name:approxHistState(m,bm.get(m.date)),spy:m.spy,vix:m.vix,b:bm.get(m.date)}))}
function currentDuration(d,h){const rows=regimeHistory(d,h),cur=regimeOf(d).name;let count=0,prev=null;for(let i=rows.length-1;i>=0;i--){const nm=i===rows.length-1?cur:rows[i].name;if(nm===cur)count++;else{prev=nm;break}}return{count,prev}}
function evidence(d){const b=d.breadth||{},s=d.etfs?.SPY||{},q=d.etfs?.QQQ||{},v=num(d.vix?.value);return[
 ['Trend',num(s.distance_ma200)>=0&&num(q.distance_ma200)>=0?'SPY and QQQ remain above their 200-day trends':'A major index is below its 200-day trend'],
 ['Breadth',num(b.above_200d)>=60?`${Number(b.above_200d).toFixed(0)}% of S&P 500 stocks remain above 200-day trends`:`Long-term participation is only ${Number(b.above_200d||0).toFixed(0)}%`],
 ['Stress',v<20?`VIX ${v?.toFixed(1)} — stress remains contained`:`VIX ${v?.toFixed(1)} — stress is elevated`],
 ['Momentum',num(b.above_5d)<50?`Only ${Number(b.above_5d).toFixed(0)}% are above 5-day trends — short-term participation is soft`:'Short-term participation is broadly healthy']
]}
function morningText(d){const r=regimeOf(d),b=d.breadth||{},v=num(d.vix?.value);let watch='Watch whether short-term breadth stabilizes and whether SPY/QQQ hold their 50-day trends.';if(num(b.above_5d)<30)watch='Breadth is already compressed. Watch for stabilization rather than assuming weakness must continue.';if(v>=20)watch+=' VIX is elevated, so volatility confirmation matters more today.';return{title:`Morning Read · ${r.name}`,text:`The official regime is ${r.name.toLowerCase()}. ${r.why} ${watch}`}}
function closingText(d,h){const r=regimeOf(d),dur=currentDuration(d,h);const changed=dur.count<=1&&dur.prev;return{title:`Closing Read · ${r.name}`,text:changed?`The market regime changed from ${dur.prev} to ${r.name}. ${r.why}`:`The regime remains ${r.name}. ${r.why} No confirmed regime change occurred at the latest close.`}}
function inject(){if(!$('condition'))return;if(!$('sessionBar')){const hero=document.querySelector('.premium-hero');hero?.insertAdjacentHTML('afterend','<div id="sessionBar" class="session-bar"><div class="session-left"><span id="sessionDot" class="session-dot"></span><div class="session-copy"><strong id="sessionLabel">Checking market session…</strong><span id="sessionDetail"></span></div></div><div id="ctClock" class="session-clock"></div></div>')}
 if(!$('dailyHabit')){const target=document.querySelector('.editorial-section');target?.insertAdjacentHTML('beforebegin','<section id="dailyHabit" class="daily-read-grid"><article class="daily-read-card"><div class="insight-label">MORNING READ</div><h3 id="morningTitle">Loading…</h3><p id="morningText"></p><div class="read-meta"><span class="read-pill">Previous confirmed close</span><span class="read-pill">What to watch today</span></div></article><article class="daily-read-card"><div class="insight-label">CLOSING READ</div><h3 id="closingTitle">Loading…</h3><p id="closingText"></p><div class="read-meta"><span class="read-pill">Confirmed daily data only</span><span class="read-pill">What actually changed</span></div></article></section>')}
 if(!$('regimeBadge')){$('condition')?.insertAdjacentHTML('afterend','<div id="regimeBadge" class="regime-badge">Building regime history…</div>')}
 if(!$('regimeEvidence')){$('summary')?.insertAdjacentHTML('afterend','<div id="regimeEvidence" class="regime-evidence"></div>')}
 if(!$('livePulse')){$('sessionBar')?.insertAdjacentHTML('afterend','<section id="livePulse" class="live-pulse" hidden><div class="live-head"><div class="live-title"><div class="insight-label">LIVE PULSE</div><h3>What is happening right now?</h3><p id="liveMeta" class="freshness"></p></div><span class="live-badge">Intraday · delayed</span></div><div id="liveGrid" class="live-grid"></div><div id="liveTake" class="live-take"></div></section>')}
 const tl=document.querySelector('.timeline-module');if(tl&&!$('transitionList'))tl.insertAdjacentHTML('beforeend','<div id="transitionList" class="transition-list"></div>');
 const intel=document.querySelector('.intelligence-section');if(intel&&!$('analogBox'))intel.insertAdjacentHTML('beforeend','<article id="analogBox" class="analog-box advanced-only"><div class="insight-label">RECENT PRECEDENT</div><h3 id="analogTitle">Finding similar market setups…</h3><p id="analogText"></p></article>')
}
function renderSession(){const s=etSession(),now=new Date();$('sessionLabel').textContent=s.label;$('sessionDetail').textContent=s.detail;$('ctClock').textContent=fmtTime(now,CT);$('sessionDot').className=`session-dot ${s.phase==='open'?'open':s.phase==='pre'?'pre':''}`;return s}
function renderDaily(d,h){const m=morningText(d),c=closingText(d,h);$('morningTitle').textContent=m.title;$('morningText').textContent=m.text;$('closingTitle').textContent=c.title;$('closingText').textContent=c.text;const dur=currentDuration(d,h);$('regimeBadge').textContent=dur.count>1?`Regime unchanged for ${dur.count} sessions`:dur.prev?`Changed from ${dur.prev} at the latest close`:'Current regime established at latest close';$('regimeEvidence').innerHTML=evidence(d).map(([k,v])=>`<div class="evidence-item"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');renderTransitions(d,h);renderAnalog(d,h)}
function renderTransitions(d,h){const rows=regimeHistory(d,h).slice(-60),runs=[];for(const row of rows){const last=runs[runs.length-1];if(last&&last.name===row.name)last.end=row.date;else runs.push({name:row.name,start:row.date,end:row.date})}$('transitionList').innerHTML=runs.slice(-5).map(x=>`<span class="transition-chip">${esc(x.name)} · ${esc(x.start)}${x.end!==x.start?' → '+esc(x.end):''}</span>`).join('')}
function renderAnalog(d,h){const market=h?.market||[],breadth=h?.breadth||[];if(market.length<60||breadth.length<60){$('analogTitle').textContent='Recent precedent is still building';$('analogText').textContent='More daily observations are needed before similar setups are useful.';return}const bm=new Map(breadth.map(x=>[x.date,x])),b=d.breadth||{},v=num(d.vix?.value),rel=num(d.relative_strength?.qqq_vs_spy_20d);const candidates=[];for(let i=0;i<market.length-21;i++){const m=market[i],bb=bm.get(m.date);if(!bb||m.relative_strength_20d==null||m.vix==null)continue;const dist=Math.abs(num(bb.above_5d)-num(b.above_5d))/20+Math.abs(num(bb.above_50d)-num(b.above_50d))/25+Math.abs(num(bb.above_200d)-num(b.above_200d))/30+Math.abs(num(m.vix)-v)/10+Math.abs(num(m.relative_strength_20d)-rel)/3;const p0=num(m.spy),p5=num(market[i+5]?.spy),p20=num(market[i+20]?.spy);if(p0&&p5&&p20)candidates.push({date:m.date,dist,r5:(p5/p0-1)*100,r20:(p20/p0-1)*100})}candidates.sort((a,b)=>a.dist-b.dist);const best=candidates.slice(0,5);if(best.length<3)return;const avg=a=>a.reduce((s,x)=>s+x,0)/a.length;$('analogTitle').textContent=`Closest recent setups: ${best.map(x=>x.date).slice(0,3).join(', ')}`;$('analogText').textContent=`Across the ${best.length} closest observations in the available history, SPY averaged ${avg(best.map(x=>x.r5)).toFixed(1)}% over the next 5 sessions and ${avg(best.map(x=>x.r20)).toFixed(1)}% over the next 20. This is context, not a forecast, and the sample is intentionally limited to the history Market Pulse currently stores.`}
async function loadLive(){const s=renderSession();if(s.phase!=='open'){$('livePulse').hidden=true;return}try{const r=await fetch(`https://raw.githubusercontent.com/arjunthak0522/market-pulse/live-data/data/live.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();const x=await r.json();lastLive=x;const now=new Date(),dt=x.data_time?new Date(x.data_time):null,age=dt?(now-dt)/60000:999,today=dateInTZ(now,ET);if(x.status!=='market_open'||x.market_date!==today||age>30){$('livePulse').hidden=true;return}$('livePulse').hidden=false;$('liveMeta').textContent=`Updated ${fmtTime(dt,CT)} · ${Math.round(age)} min old · official regime still based on previous close`;const sp=x.etfs?.SPY||{},q=x.etfs?.QQQ||{};const vals=[['SPY',sp.change_pct,sp.price],['QQQ',q.change_pct,q.price],['VIX',null,x.vix],['DATA AGE',null,`${Math.round(age)} min`]];$('liveGrid').innerHTML=vals.map(([k,ch,px])=>`<div class="live-metric"><span>${k}</span><strong>${typeof px==='number'?(k==='VIX'?px.toFixed(1):'$'+px.toFixed(2)):esc(px)}</strong>${ch!=null?`<small>${ch>=0?'+':''}${Number(ch).toFixed(2)}% today</small>`:''}</div>`).join('');let threats=[];if(lastDaily){const d=lastDaily,derive=(sym,key)=>{const e=d.etfs?.[sym]||{},close=num(e.price),dist=num(e[key]);return close&&dist!=null?close/(1+dist/100):null};const s50=derive('SPY','distance_ma50'),q50=derive('QQQ','distance_ma50');if(s50&&num(sp.price)<s50)threats.push('SPY is trading below its closing 50-day trend');if(q50&&num(q.price)<q50)threats.push('QQQ is trading below its closing 50-day trend');if(num(x.vix)>=20)threats.push('VIX is above 20')} $('liveTake').textContent=threats.length?`Intraday warning: ${threats.join('; ')}. These conditions can threaten the closing thesis, but they do not change the official regime until confirmed at the close.`:'No major intraday condition is currently threatening the official closing thesis.';maybeNotifyThreat(threats)}catch{$('livePulse').hidden=true}}
function maybeNotifyThreat(threats){if(!threats.length)return;try{const key=`${dateInTZ(new Date(),ET)}:${threats.join('|')}`,last=localStorage.getItem('marketPulseLiveThreat');if(last!==key&&'Notification'in window&&Notification.permission==='granted'){new Notification('Market Pulse · Live thesis watch',{body:threats[0]});localStorage.setItem('marketPulseLiveThreat',key)}}catch{}}
async function boot(){inject();try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(dr.ok){lastDaily=await dr.json();lastHist=hr.ok?await hr.json():{};renderDaily(lastDaily,lastHist)}}catch{}renderSession();loadLive();setInterval(()=>{renderSession();loadLive()},60000)}
window.addEventListener('DOMContentLoaded',()=>setTimeout(boot,50));
})();
