(()=>{
const $=id=>document.getElementById(id);
const n=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const pct=(values,value)=>{const xs=(values||[]).map(n).filter(v=>v!=null);if(value==null||xs.length<20)return null;return 100*xs.filter(v=>v<=value).length/xs.length};
const fmtPct=v=>v==null?'—':`${Math.round(v)}th percentile`;
const niceDate=v=>{if(!v)return'latest close';try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${v}T12:00:00Z`))}catch{return v}};
function band(p,high=true){if(p==null)return null;const extreme=high?p>=90:p<=10;if(!extreme)return null;const severe=high?p>=97.5:p<=2.5;return severe?'severe':'extreme'}
function add(list,x){if(x&&x.level)list.push(x)}
function signal({id,title,value,percentile,level,plain,why,target,source,detail}){return{id,title,value,percentile,level,plain,why,target,source,detail}}
function detect(ctx,hist){
  const out=[],breadthRows=hist.breadth||[],pcRows=hist.put_call||[],marketRows=hist.market||[];
  const b=ctx.breadth||{},pc=ctx.equity_put_call||{},vix=n(ctx.vix?.value),m=ctx.mcclellan||{};
  const pcv=n(pc.value),pcp=pct(pcRows.slice(-252).map(x=>x.value),pcv)??n(pc.percentile_60d);
  add(out,signal({id:'cpce',title:'Equity options fear',value:pcv==null?'—':pcv.toFixed(2),percentile:pcp,level:band(pcp,true),plain:'Equity put buying is unusually heavy versus call buying.',why:'Extreme equity put/call readings can mark defensive positioning and potential exhaustion, but they are not reversal signals by themselves.',target:'#marketContext',source:pc.source||'Cboe Equity Put/Call Ratio',detail:`${fmtPct(pcp)} vs available history`}));
  const trin=n(b.trin),trinp=pct(breadthRows.slice(-252).map(x=>x.trin),trin);
  add(out,signal({id:'trin',title:'Capitulation pressure',value:trin==null?'—':trin.toFixed(2),percentile:trinp,level:band(trinp,true),plain:'Selling volume is unusually concentrated in declining stocks.',why:'TRIN combines issue breadth with volume breadth, so an extreme spike can identify panic-like selling pressure.',target:'.breadth-module',source:b.trin_method||'Arms Index',detail:`${fmtPct(trinp)} vs 1 year`}));
  const b5=n(b.above_5d),b5p=pct(breadthRows.slice(-252).map(x=>x.above_5d),b5);
  add(out,signal({id:'breadth5',title:'Short-term breadth washout',value:b5==null?'—':`${b5.toFixed(0)}%`,percentile:b5p,level:band(b5p,false),plain:'Very few S&P 500 stocks are holding their short-term trend.',why:'A broad washout is more meaningful than one oversold index because weakness is occurring across many stocks at once.',target:'.breadth-module',source:b.source||'S&P 500 constituent breadth',detail:`${fmtPct(b5p)} vs 1 year`}));
  const lows=n(b.new_lows_52w),issues=(n(b.advancers)||0)+(n(b.decliners)||0)+(n(b.unchanged)||0),lowShare=issues>0?100*lows/issues:null;
  const structuralLevel=lowShare!=null&&lowShare>=5?(lowShare>=10?'severe':'extreme'):null;
  add(out,signal({id:'newlows',title:'52-week low pressure',value:lowShare==null?'—':`${lowShare.toFixed(1)}%`,percentile:null,level:structuralLevel,plain:'An unusually large share of stocks is making fresh 52-week lows.',why:'New-low expansion helps distinguish a routine pullback from spreading structural damage.',target:'.breadth-module',source:'S&P 500 constituent 52-week lows',detail:lows==null?'Current value unavailable':`${lows} stocks at 52-week lows`}));
  const vixp=pct(marketRows.slice(-252).map(x=>x.vix),vix);
  add(out,signal({id:'vix',title:'Volatility stress',value:vix==null?'—':vix.toFixed(1),percentile:vixp,level:band(vixp,true),plain:'Option-implied volatility is unusually elevated.',why:'VIX extremes show urgency in risk pricing. They are strongest when confirmed by breadth and options-positioning stress.',target:'#marketContext',source:ctx.vix?.source||'Cboe VIX',detail:`${fmtPct(vixp)} vs 1 year`}));
  [['namo','Nasdaq breadth extreme','Nasdaq breadth momentum is at an unusual extreme.','Nasdaq McClellan Oscillator'],['nymo','NYSE breadth extreme','Broad-market breadth momentum is at an unusual extreme.','NYSE McClellan Oscillator']].forEach(([key,title,plain,src])=>{const row=m[key]||{},val=n(row.value),p=n(row.percentile_252d);if(val==null||p==null)return;const level=p>=90||p<=10?(p>=97.5||p<=2.5?'severe':'extreme'):null;add(out,signal({id:key,title,value:val.toFixed(0),percentile:p,level,plain,why:'McClellan extremes measure unusually strong breadth momentum and can identify washouts or breadth thrusts.',target:'.breadth-module',source:row.source||src,detail:`${fmtPct(p)} vs 1 year`}))});
  return out.sort((a,b)=>{const rank=x=>x.level==='severe'?2:1;return rank(b)-rank(a)||Math.abs((b.percentile??50)-50)-Math.abs((a.percentile??50)-50)}).slice(0,5)
}
function synthesis(xs){
  const ids=new Set(xs.map(x=>x.id));
  if(ids.has('cpce')&&(ids.has('breadth5')||ids.has('trin')))return 'Options positioning and market internals are simultaneously stretched. That raises the odds of a short-term exhaustion setup, but the dashboard still needs evidence that buyers are returning before treating it as a reversal.';
  if(ids.has('newlows')&&(ids.has('breadth5')||ids.has('vix')))return 'Weakness is spreading beneath the indexes and is no longer just a momentum story. Watch whether new lows keep expanding or begin to contract before assuming the pullback is stabilizing.';
  if(ids.has('namo')||ids.has('nymo'))return 'Breadth momentum has reached an unusual extreme. The next useful information is whether participation continues deteriorating or snaps back in a breadth-thrust style reversal.';
  if(xs.length)return 'At least one market input has moved far enough from normal to deserve attention. Treat the extreme as context, then look for confirmation from participation, price structure, and risk pricing.';
  return 'No tracked indicator is far enough from its recent distribution to qualify as a meaningful extreme today.'
}
function card(x){return `<button class="extreme-card ${x.level}" type="button" data-target="${x.target||''}"><div class="extreme-card-top"><span>${x.title}</span><strong>${x.value}</strong></div><div class="extreme-rank">${x.detail}</div><p>${x.plain}</p><small>${x.why}</small><div class="extreme-source">${x.source||''}<span>View evidence ›</span></div></button>`}
function jump(target){if(!target)return;const node=document.querySelector(target);if(!node)return;if(node.tagName==='DETAILS')node.open=true;node.scrollIntoView({behavior:'smooth',block:'start'})}
function ensure(){let sec=$('meaningfulExtremes');if(sec)return sec;sec=document.createElement('section');sec.id='meaningfulExtremes';sec.className='extremes-section';const anchor=$('briefingV2')||document.querySelector('.intelligence-section');anchor?.insertAdjacentElement('afterend',sec);return sec}
async function boot(){const sec=ensure();if(!sec)return;try{const t=Date.now(),[cr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!cr.ok||!hr.ok)throw Error('extreme data unavailable');const ctx=await cr.json(),hist=await hr.json(),xs=detect(ctx,hist);sec.innerHTML=`<div class="extremes-head"><div><div class="eyebrow">TODAY'S MEANINGFUL EXTREMES</div><h2>${xs.length?`${xs.length} unusual signal${xs.length===1?'':'s'} detected`:'Nothing unusually stretched today'}</h2><p>Only readings far from normal are surfaced. Routine indicators stay hidden.</p></div><div class="extremes-date">${niceDate(ctx.market_date)}</div></div>${xs.length?`<div class="extremes-grid">${xs.map(card).join('')}</div>`:'<div class="extremes-empty">No tracked extreme crossed its alert threshold at the latest close.</div>'}<div class="extremes-synthesis"><span>WHAT IT MEANS</span><strong>${synthesis(xs)}</strong></div><div class="extremes-actions"><button type="button" id="extremeHistory">See historical outcomes</button><span>CPCE · NAMO · NYMO · TRIN · new lows · breadth · volatility</span></div>`;sec.querySelectorAll('[data-target]').forEach(btn=>btn.addEventListener('click',()=>jump(btn.dataset.target)));$('extremeHistory')?.addEventListener('click',()=>jump('#historicalForwardReturns'));window.dispatchEvent(new CustomEvent('market-extremes-rendered',{detail:{count:xs.length,signals:xs.map(x=>x.id)}}))}catch(e){sec.innerHTML='<div class="extremes-empty"><strong>Meaningful extremes are temporarily unavailable.</strong></div>';console.warn('Market Pulse extremes:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot,{once:true});else boot();document.getElementById('refresh')?.addEventListener('click',boot);
})();
