(()=>{
const $=id=>document.getElementById(id);const n=v=>Number.isFinite(Number(v))?Number(v):null;
const replacements={
 '% above 5-day MA':'One-week participation','% above 20-day MA':'One-month participation','% above 50-day MA':'Intermediate participation','% above 200-day MA':'Long-term participation',
 'Distance from 20-day MA':'Short-term trend position','Distance from 50-day MA':'Intermediate trend position','Distance from 200-day MA':'Long-term trend position',
 'QQQ vs SPY · 20D':'Growth vs broad-market leadership','50-DAY BREADTH · 60 SESSIONS':'INTERMEDIATE PARTICIPATION · 60 SESSIONS'
};
function replaceText(root=document){root.querySelectorAll('.name,.insight-label,.intel-label,.section-step,.health-cell-head span,.trend-table th').forEach(el=>{const t=el.textContent.trim();if(replacements[t])el.textContent=replacements[t]})}
function renameHealth(){document.querySelectorAll('#healthGrid .health-cell').forEach((c,i)=>{const s=c.querySelector('.health-cell-head span');if(!s)return;const labels=['PRIMARY TREND','MARKET PARTICIPATION','MARKET STRESS','MARKET LEADERSHIP','PRICE MOMENTUM'];if(labels[i])s.textContent=labels[i]})}
function renameTrendTable(){const hs=document.querySelectorAll('.trend-table thead th');const labels=['INDEX','SHORT TERM\n20-DAY','INTERMEDIATE\n50-DAY','LONG TERM\n200-DAY'];hs.forEach((h,i)=>{if(labels[i])h.innerHTML=labels[i].replace('\n','<small>')+(labels[i].includes('\n')?'</small>':'')})}
function renameTurning(){document.querySelectorAll('#tpGrid .tp-card').forEach(c=>{const label=c.querySelector('.tp-card-top span'),small=c.querySelector('.tp-card-top small');if(!label)return;const t=label.textContent.trim();if(t==='A/D BREADTH'){label.textContent='DAILY PARTICIPATION BALANCE';if(small)small.textContent='Advancers vs decliners'}else if(t==='RSI BREADTH'){label.textContent='STOCKS ALREADY OVERSOLD';if(small)small.textContent='Breadth exhaustion'}else if(t==='S&P 500 TRIN'){label.textContent='SELLING-VOLUME PRESSURE';if(small)small.textContent='S&P 500 TRIN · Arms-style'}})}
function plainWatch(){const h=$('guideWatchHeadline'),p=$('guideWatchText');if(h){const map={'50-day breadth':'Intermediate participation','50-day repair':'Intermediate trend repair','200-day repair':'Long-term trend repair','Volatility normalization':'Fear cooling','Participation beneath the indexes':'Participation beneath the indexes'};const k=h.textContent.trim();if(map[k])h.textContent=map[k]}
 if(p){p.textContent=p.textContent.replace(/50-day breadth/gi,'intermediate participation').replace(/50-day (average|trend)/gi,'intermediate trend').replace(/200-day (average|trend)/gi,'long-term trend').replace(/20-day (average|trend)/gi,'short-term trend')}}
function explainBreadthHeader(){const m=document.querySelector('.breadth-module');if(!m)return;const eye=m.querySelector('.eyebrow'),h=m.querySelector('h2'),p=m.querySelector('.module-header p');if(eye)eye.textContent='MARKET PARTICIPATION';if(h)h.textContent='Is the strength or weakness broad across the market?';if(p)p.textContent='This shows how many S&P 500 stocks are participating across short-, intermediate-, and long-term trends. Broad participation makes index moves more durable.'}
function simplifyHero(){const chips=$('chips');if(chips){chips.innerHTML='';chips.hidden=true}const cells=document.querySelectorAll('#premiumStateStrip .state-cell span');const labels=['PRIMARY TREND','PARTICIPATION','STRESS'];cells.forEach((x,i)=>{if(labels[i])x.textContent=labels[i]})}
function morningCopy(d){const card=$('morningCard');if(!card)return;const b=d.breadth||{},s=d.etfs?.SPY||{},q=d.etfs?.QQQ||{},b5=n(b.above_5d),b50=n(b.above_50d),v=n(d.vix?.value);let first='The prior close still points to an intact primary trend.';if(n(s.distance_ma200)<0||n(q.distance_ma200)<0)first='The prior close shows long-term trend damage that still needs repair.';let participation=b5==null?'Short-term participation is unavailable.':b5<30?`Only ${b5.toFixed(0)}% of S&P 500 stocks are holding above their one-week trend, so selling has become broad.`:b5<50?`${b5.toFixed(0)}% of S&P 500 stocks are holding above their one-week trend, showing softer short-term participation.`:`${b5.toFixed(0)}% of S&P 500 stocks are holding above their one-week trend, so short-term participation is healthy.`;let watch=b50!=null&&b50<50?'Watch whether intermediate participation recovers or keeps fading beneath the indexes.':'Watch whether intermediate participation stays healthy and whether SPY/QQQ hold their intermediate trend support.';if(v!=null&&v>=20)watch+=' Volatility is elevated, so further stress deserves more weight.';const t=$('morningText');if(t)t.textContent=`${first} ${participation} ${watch} The official regime changes only after a confirmed close.`}
function scanCards(){document.querySelectorAll('.card .name').forEach(el=>{const t=el.textContent.trim();if(replacements[t])el.textContent=replacements[t]});document.querySelectorAll('.card p').forEach(p=>{p.textContent=p.textContent.replace(/5-day average/gi,'one-week trend').replace(/20-day average/gi,'one-month trend').replace(/50-day average/gi,'intermediate trend').replace(/200-day average/gi,'long-term trend')})}
function apply(d){simplifyHero();renameHealth();renameTrendTable();renameTurning();plainWatch();explainBreadthHeader();replaceText();scanCards();morningCopy(d);document.querySelectorAll('.breadth-row').forEach(row=>{const t=row.textContent; if(/5-day/i.test(t)) row.setAttribute('aria-label','One-week market participation'); if(/20-day/i.test(t)) row.setAttribute('aria-label','One-month market participation'); if(/50-day/i.test(t)) row.setAttribute('aria-label','Intermediate market participation'); if(/200-day/i.test(t)) row.setAttribute('aria-label','Long-term market participation')})}
async function boot(){try{const r=await fetch(`data/market_context.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();for(const ms of [0,350,900,1600,2600])setTimeout(()=>apply(d),ms)}catch(e){console.warn('Investor clarity:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();
document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(boot,900));
})();