(()=>{
const $=id=>document.getElementById(id),n=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null),f=(v,d=1)=>n(v)==null?'—':n(v).toFixed(d);
function card(label,value,status,copy,tech){return `<article class="risk-card"><div class="risk-card-top"><span>${label}</span><strong>${value}</strong></div><h3>${status}</h3><p>${copy}</p><details><summary>What is this?</summary><p>${tech}</p></details></article>`}
function render(d){const host=document.querySelector('.shared-context'),grid=$('marketContext');if(!host||!grid)return;const o=d.options_risk||{},ratio=n(o.vix_vix3m_ratio),vvix=n(o.vvix),vvp=n(o.vvix_percentile_252d),skew=n(o.skew),skp=n(o.skew_percentile_252d),pc=n(d.equity_put_call?.value),pcp=n(d.equity_put_call?.percentile_60d);
 const urgent=ratio==null?['Unavailable','Fear timing data is unavailable.']:ratio>1?['Acute stress','Near-term fear is above the three-month outlook.']:ratio>=.95?['Stress building','The normal volatility-curve cushion is nearly gone.']:['Normal structure','Near-term fear remains below the three-month outlook.'];
 const vv=vvix==null?['Unavailable','VVIX data is unavailable.']:vvp!=null&&vvp>=90?['Shock risk elevated','Volatility expectations are being repriced unusually aggressively.']:vvp!=null&&vvp>=75?['Uncertainty elevated','Volatility uncertainty is above normal.']:['Normal uncertainty','No unusual volatility-of-volatility signal is present.'];
 const pp=pc==null?['Unavailable','Positioning data is unavailable.']:pcp!=null&&pcp>=90?['Unusually defensive','Downside hedging is near a recent extreme.']:pcp!=null&&pcp<=20?['Relatively complacent','Downside hedging is light versus recent history.']:['Ordinary positioning','Options positioning is not at a meaningful extreme.'];
 const ss=skew==null?['Unavailable','Crash-insurance pricing is unavailable.']:skp!=null&&skp>=90?['Protection expensive','Crash insurance is unusually expensive versus the last year.']:skp!=null&&skp>=75?['Demand elevated','Tail-risk protection demand is above normal.']:['Normal demand','Tail-risk pricing is within a normal range.'];
 const warnings=Number(ratio!=null&&ratio>=.95)+Number(vvp!=null&&vvp>=75)+Number(pcp!=null&&pcp>=75)+Number(skp!=null&&skp>=75);let headline='Options risk remains contained',copy='Risk pricing is not broadly confirming an acute stress regime.',watch='A flattening or inverted volatility curve plus rising VVIX would materially worsen the read.';if(warnings>=3){headline='Risk pricing broadly deteriorating';copy='At least three independent options-risk measures are elevated together.';watch='Watch whether term structure and VVIX begin to normalize.'}else if(warnings>=2){headline='Risk pricing is deteriorating';copy='More than one options-market measure is showing increased caution.';watch='Broadening stress would matter more than any one indicator.'}
 let summary=$('optionsRiskSummary');if(!summary){summary=document.createElement('article');summary.id='optionsRiskSummary';summary.className='options-risk-summary';host.querySelector('.context-layout')?.before(summary)}summary.innerHTML=`<div class="insight-label">OPTIONS-MARKET READ</div><h3>${headline}</h3><p>${copy}</p><div class="options-risk-watch"><b>WHAT MATTERS NEXT</b><span>${watch}</span></div>`;
 grid.className='options-risk-grid';grid.innerHTML=[card('HOW URGENT IS FEAR?',ratio==null?'—':`${f(ratio,2)}×`,urgent[0],urgent[1],'Technical: VIX divided by VIX3M. Above 1 means near-term volatility is above the three-month outlook.'),card('VOLATILITY INSTABILITY',vvp==null?f(vvix,1):`${Math.round(vvp)}th pct`,vv[0],vv[1],'Technical: VVIX, the volatility of VIX. Percentiles compare with up to 252 sessions.'),card('HOW DEFENSIVE ARE TRADERS?',pcp==null?f(pc,2):`${Math.round(pcp)}th pct`,pp[0],pp[1],'Technical: equity put/call ratio. Higher readings indicate more downside hedging.'),card('CRASH-INSURANCE DEMAND',skp==null?f(skew,1):`${Math.round(skp)}th pct`,ss[0],ss[1],'Technical: CBOE SKEW. High readings mean protection against large downside moves is relatively expensive.')].join('');host.querySelector('.context-viz')?.setAttribute('hidden','');
}
async function boot(){try{const r=await fetch('data/market_context.json',{cache:'no-store'});if(r.ok)render(await r.json())}catch(e){console.warn('Options risk:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot,{once:true});else boot();document.getElementById('refresh')?.addEventListener('click',boot);
})();
