(()=>{
const $=id=>document.getElementById(id);
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function spark(values,strokeClass='line',area=true){const a=values.map(num).filter(v=>v!=null);if(a.length<2)return'<div class="spark-empty">History building</div>';const w=320,h=92,p=5,min=Math.min(...a),max=Math.max(...a),range=max-min||1;const pts=a.map((v,i)=>`${p+(w-2*p)*(i/(a.length-1))},${p+(h-2*p)*(1-(v-min)/range)}`).join(' ');const areaPts=`${p},${h-p} ${pts} ${w-p},${h-p}`;return `<svg class="sparkline light-spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><line class="grid" x1="0" y1="${h*.5}" x2="${w}" y2="${h*.5}"/>${area?`<polygon class="area" points="${areaPts}"/>`:''}<polyline class="${strokeClass}" points="${pts}"/></svg>`}
function trendState(spy,qqq,b){const s=num(spy.distance_ma50),q=num(qqq.distance_ma50),long=num(b.above_200d);if((s??0)<0||(q??0)<0)return['Under pressure','warn'];if(long!=null&&long<50)return['Mixed','warn'];return['Healthy','good']}
function breadthState(b){const b5=num(b.above_5d),b50=num(b.above_50d),b200=num(b.above_200d);if(b200!=null&&b200<40)return['Weak','bad'];if(b50!=null&&b50<40)return['Weakening','warn'];if(b5!=null&&b5<50)return['Soft short term','warn'];return['Healthy','good']}
function momentumState(spy,qqq){const vals=[num(spy.rsi14),num(qqq.rsi14)].filter(x=>x!=null),w=[num(spy.williams_r14),num(qqq.williams_r14)].filter(x=>x!=null);if(w.some(x=>x<-80)||vals.some(x=>x<35))return['Oversold','warn'];if(w.some(x=>x>-20)||vals.some(x=>x>70))return['Overbought','warn'];if(vals.length&&Math.min(...vals)<45)return['Soft','warn'];if(vals.length&&Math.max(...vals)>60)return['Firm','good'];return['Neutral','']}
function stressState(v){if(v==null)return['Unavailable',''];if(v<20)return['Low','good'];if(v<30)return['Rising','warn'];return['High','bad']}
function leadershipState(rel){if(rel==null)return['Unavailable',''];if(rel>1)return['Growth / Tech leading','good'];if(rel<-1)return['Broad market leading',''];return['Balanced','']}
function setMode(mode){const advanced=mode==='advanced';document.body.classList.toggle('mode-advanced',advanced);document.body.classList.toggle('mode-simple',!advanced);$('viewSimple')?.classList.toggle('active',!advanced);$('viewAdvanced')?.classList.toggle('active',advanced);$('viewSimple')?.setAttribute('aria-pressed',String(!advanced));$('viewAdvanced')?.setAttribute('aria-pressed',String(advanced));try{localStorage.setItem('marketPulseViewV2',advanced?'advanced':'simple')}catch{}}
function savedMode(){try{return localStorage.getItem('marketPulseViewV2')==='simple'?'simple':'advanced'}catch{return'advanced'}}
function relabelViews(){const overview=$('viewSimple'),full=$('viewAdvanced'),group=overview?.parentElement;if(overview){overview.textContent='Overview';overview.title='Key conclusions and market context';overview.setAttribute('aria-label','Overview: key conclusions and market context')}if(full){full.textContent='Full Analysis';full.title='All charts, historical detail and technical evidence';full.setAttribute('aria-label','Full Analysis: all charts, historical detail and technical evidence')}if(group)group.setAttribute('aria-label','Choose dashboard view: Overview or Full Analysis')}
function applyPlainLanguage(d){const spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},b=d.breadth||{},v=num(d.vix?.value),rel=num(d.relative_strength?.qqq_vs_spy_20d);const states=[['TREND',trendState(spy,qqq,b)],['BREADTH',breadthState(b)],['MOMENTUM',momentumState(spy,qqq)],['STRESS',stressState(v)],['LEADERSHIP',leadershipState(rel)]];
 if($('briefBullets'))$('briefBullets').innerHTML=states.map(([k,[s]])=>`<div class="brief-bullet"><span>${k}</span><strong>${esc(s)}</strong></div>`).join('');
 const leadership=leadershipState(rel)[0];if($('spyLeadership'))$('spyLeadership').textContent=leadership;if($('qqqLeadership'))$('qqqLeadership').textContent=leadership;
 const alignment=$('alignmentHeadline')?.textContent||'';if($('briefText')){const r=typeof regime==='function'?regime(d):null;let txt=r?.why||$('briefText').textContent;if(alignment.toLowerCase().includes('diverg'))txt+=` One internal signal is not fully aligned, so watch confirmation rather than reacting to one indicator.`;$('briefText').textContent=txt}
}
function render(d,h){const spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},b=d.breadth||{},v=num(d.vix?.value),rel=num(d.relative_strength?.qqq_vs_spy_20d);if($('premiumAsOf'))$('premiumAsOf').textContent=`As of ${d.market_date||'latest close'} · daily-session methodology`;const market=h?.market||[],breadth=h?.breadth||[];if($('heroSpark'))$('heroSpark').innerHTML=spark(market.slice(-60).map(x=>x.spy));const cells=[['Trend',trendState(spy,qqq,b)],['Breadth',breadthState(b)],['Momentum',momentumState(spy,qqq)],['Stress',stressState(v)],['Leadership',leadershipState(rel)]];if($('premiumStateStrip'))$('premiumStateStrip').innerHTML=cells.map(([k,[s,t]])=>`<div class="state-cell"><span>${k}</span><strong><i class="${t}"></i>${esc(s)}</strong></div>`).join('');if($('breadthSpark'))$('breadthSpark').innerHTML=spark(breadth.slice(-60).map(x=>x.above_50d));if($('vixSpark'))$('vixSpark').innerHTML=spark(market.slice(-60).map(x=>x.vix),'line',false);if($('leadershipSpark'))$('leadershipSpark').innerHTML=spark(market.slice(-60).map(x=>x.relative_strength_20d),'line',false);const spyMove=num(spy.change_pct),qqqMove=num(qqq.change_pct);if($('spyTabMove'))$('spyTabMove').textContent=spyMove==null?'—':`${spyMove>=0?'+':''}${spyMove.toFixed(2)}%`;if($('qqqTabMove'))$('qqqTabMove').textContent=qqqMove==null?'—':`${qqqMove>=0?'+':''}${qqqMove.toFixed(2)}%`;if($('spyMini'))$('spyMini').innerHTML=spark(market.slice(-45).map(x=>x.spy));if($('qqqMini'))$('qqqMini').innerHTML=spark(market.slice(-45).map(x=>x.qqq));const breadthTrend=num(b.above_50d),long=num(b.above_200d);if($('premiumOneLine'))$('premiumOneLine').textContent=long>=60&&breadthTrend>=40?'Long-term structure is healthy. Watch whether short-term weakness repairs or spreads.':long>=50?'The long-term structure is mixed. Participation deserves closer attention.':'Long-term participation is deteriorating.';applyPlainLanguage(d);setTimeout(()=>applyPlainLanguage(d),500)}
async function boot(){try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!dr.ok)return;render(await dr.json(),hr.ok?await hr.json():{});}catch(e){console.warn('Premium layer:',e)}}
window.addEventListener('DOMContentLoaded',()=>{relabelViews();setMode(savedMode());$('viewSimple')?.addEventListener('click',()=>setMode('simple'));$('viewAdvanced')?.addEventListener('click',()=>setMode('advanced'));setTimeout(boot,0)});const refresh=$('refresh');if(refresh)refresh.addEventListener('click',()=>setTimeout(boot,450));
})();
