(()=>{
const $=id=>document.getElementById(id);
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function spark(values,strokeClass='line',area=true){const a=values.map(num).filter(v=>v!=null);if(a.length<2)return'<div class="spark-empty">History building</div>';const w=320,h=92,p=5,min=Math.min(...a),max=Math.max(...a),range=max-min||1;const pts=a.map((v,i)=>`${p+(w-2*p)*(i/(a.length-1))},${p+(h-2*p)*(1-(v-min)/range)}`).join(' ');const areaPts=`${p},${h-p} ${pts} ${w-p},${h-p}`;return `<svg class="sparkline light-spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><line class="grid" x1="0" y1="${h*.5}" x2="${w}" y2="${h*.5}"/>${area?`<polygon class="area" points="${areaPts}"/>`:''}<polyline class="${strokeClass}" points="${pts}"/></svg>`}
function stateTone(type,val){if(val==null)return['Unavailable',''];if(type==='trend')return val>=0?['Intact','good']:['Under pressure','warn'];if(type==='breadth')return val>=60?['Healthy','good']:val>=40?['Mixed','warn']:['Weak','bad'];if(type==='momentum')return val<35?['Oversold','warn']:val>65?['Strong','good']:['Neutral',''];if(type==='stress')return val<20?['Low','good']:val<30?['Rising','warn']:['High','bad'];if(type==='leadership')return val>1?['QQQ leading','good']:val<-1?['SPY leading','']:['Balanced',''];return['Mixed','']}
function histMap(arr){const m=new Map();(arr||[]).forEach(x=>m.set(x.date,x));return m}
function simpleRegime(row,b){const s=row?.spy, v=row?.vix, b5=b?.above_5d,b50=b?.above_50d,b200=b?.above_200d;if(v!=null&&v>=30)return'bad';if(b200!=null&&b200<40)return'bad';if((b5!=null&&b5<25)||(b50!=null&&b50<40))return'warn';if(s!=null&&b200!=null&&b200>=60)return'good';return''}
function render(d,h){const spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},b=d.breadth||{},v=num(d.vix?.value),rel=num(d.relative_strength?.qqq_vs_spy_20d);const r=typeof regime==='function'?regime(d):{name:'Market read',why:''};
 if($('premiumRegime'))$('premiumRegime').textContent=r.name;if($('premiumThesis'))$('premiumThesis').textContent=r.why;if($('premiumAsOf'))$('premiumAsOf').textContent=`As of ${d.market_date||'latest close'} · daily-session methodology`;
 const market=h?.market||[],breadth=h?.breadth||[];if($('heroSpark'))$('heroSpark').innerHTML=spark(market.slice(-60).map(x=>x.spy));
 const cells=[['Trend',stateTone('trend',Math.min(num(spy.distance_ma50)??0,num(qqq.distance_ma50)??0))],['Breadth',stateTone('breadth',num(b.above_50d))],['Momentum',stateTone('momentum',num(spy.rsi14))],['Stress',stateTone('stress',v)],['Leadership',stateTone('leadership',rel)]];if($('premiumStateStrip'))$('premiumStateStrip').innerHTML=cells.map(([k,[s,t]])=>`<div class="state-cell"><span>${k}</span><strong><i class="${t}"></i>${esc(s)}</strong></div>`).join('');
 if($('breadthSpark'))$('breadthSpark').innerHTML=spark(breadth.slice(-60).map(x=>x.above_50d));if($('vixSpark'))$('vixSpark').innerHTML=spark(market.slice(-60).map(x=>x.vix), 'line', false);if($('leadershipSpark'))$('leadershipSpark').innerHTML=spark(market.slice(-60).map(x=>x.relative_strength_20d), 'line', false);
 const bm=histMap(breadth), recent=market.slice(-45);if($('regimeTimeline'))$('regimeTimeline').innerHTML=recent.map(x=>`<span class="regime-seg ${simpleRegime(x,bm.get(x.date))}" title="${esc(x.date)}"></span>`).join('');
 const spyMove=num(spy.change_pct),qqqMove=num(qqq.change_pct);if($('spyTabMove'))$('spyTabMove').textContent=spyMove==null?'—':`${spyMove>=0?'+':''}${spyMove.toFixed(2)}%`;if($('qqqTabMove'))$('qqqTabMove').textContent=qqqMove==null?'—':`${qqqMove>=0?'+':''}${qqqMove.toFixed(2)}%`;
 if($('spyMini'))$('spyMini').innerHTML=spark(market.slice(-45).map(x=>x.spy));if($('qqqMini'))$('qqqMini').innerHTML=spark(market.slice(-45).map(x=>x.qqq));
 const breadthTrend=num(b.above_50d), long=num(b.above_200d);if($('premiumOneLine'))$('premiumOneLine').textContent=long>=60&&breadthTrend>=40?'Long-term structure remains supportive; focus on whether short-term weakness broadens or repairs.':long>=50?'Structure is mixed; intermediate participation deserves closer attention.':'Long-term participation is deteriorating and deserves defensive attention.';
}
async function boot(){try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!dr.ok)return;render(await dr.json(),hr.ok?await hr.json():{});}catch(e){console.warn('Premium layer:',e)}}
window.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));const refresh=$('refresh');if(refresh)refresh.addEventListener('click',()=>setTimeout(boot,450));
})();
