(()=>{
const $=id=>document.getElementById(id),num=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const values=(rows,key)=>(rows||[]).map(r=>num(r?.[key])).filter(v=>v!=null);
const percentile=(rows,key,value)=>{const xs=values(rows,key).slice(-252);if(value==null||xs.length<20)return null;return 100*xs.filter(v=>v<=value).length/xs.length};
const avg=(xs,n=5)=>{const a=(xs||[]).slice(-n).map(num).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};
const quantile=(xs,q)=>{const a=xs.filter(v=>Number.isFinite(v)).sort((a,b)=>a-b);if(!a.length)return null;const pos=(a.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(pos-lo)};
const median=xs=>quantile(xs,.5);
const ordinal=p=>p==null?'Percentile unavailable':`${Math.round(p)}${[11,12,13].includes(Math.round(p)%100)?'th':({1:'st',2:'nd',3:'rd'}[Math.round(p)%10]||'th')} percentile`;
const statusFromPct=(p,high=true)=>{if(p==null)return'normal';if((high&&p>=97.5)||(!high&&p<=2.5))return'severe';if((high&&p>=90)||(!high&&p<=10))return'extreme';return'normal'};
const fmtReturn=v=>v==null?'—':`${v>=0?'+':''}${v.toFixed(1)}%`;
function forwardStats(returns){if(!returns.length)return null;return{n:returns.length,average:returns.reduce((a,b)=>a+b,0)/returns.length,median:median(returns),positive_rate:100*returns.filter(x=>x>0).length/returns.length,best:Math.max(...returns),worst:Math.min(...returns)}}
function buildRecordedStudy(hist,{id,title,rule,sourceRows,field,high}){const market=hist.market||[],spyIndex=new Map(market.map((r,i)=>[r.date,i])),xs=values(sourceRows,field);if(xs.length<40||market.length<80)return null;const threshold=quantile(xs,high?.9:.1),hits=[];for(const row of sourceRows){const v=num(row?.[field]),i=spyIndex.get(row?.date);if(v==null||i==null)continue;if((high&&v>=threshold)||(!high&&v<=threshold))hits.push({date:row.date,index:i,value:v})}if(hits.length<5)return null;const horizons={};for(const h of [5,10,21,60]){const rs=[];for(const hit of hits){const start=num(market[hit.index]?.spy),end=num(market[hit.index+h]?.spy);if(start!=null&&end!=null)rs.push(100*(end/start-1))}const s=forwardStats(rs);if(s)horizons[h]=s}if(!Object.keys(horizons).length)return null;return{id,title,rule,threshold,high,horizons,prior_dates:hits.map(x=>x.date).slice(-12).reverse(),sample:hits.length,source:'Market Pulse recorded history'}}
function studiesFromHistory(hist){return{
 trin:buildRecordedStudy(hist,{id:'trin',title:'TRIN capitulation extremes',rule:'TRIN closes in the top decile of Market Pulse recorded history.',sourceRows:hist.breadth||[],field:'trin',high:true}),
 breadth:buildRecordedStudy(hist,{id:'breadth',title:'Short-term breadth washouts',rule:'5-day breadth closes in the bottom decile of Market Pulse recorded history.',sourceRows:hist.breadth||[],field:'above_5d',high:false}),
 vol:buildRecordedStudy(hist,{id:'vol',title:'VIX stress extremes',rule:'VIX closes in the top decile of Market Pulse recorded history.',sourceRows:hist.market||[],field:'vix',high:true})
}}
function makeSignals(ctx,hist,studies){const b=ctx.breadth||{},br=hist.breadth||[],m=ctx.mcclellan||{},risk=ctx.options_risk||{},market=hist.market||[];
 const namo=num(m.namo?.value),namoPct=num(m.namo?.percentile_252d),nymo=num(m.nymo?.value),nymoPct=num(m.nymo?.percentile_252d);
 const trin=num(b.trin),trinPct=percentile(br,'trin',trin),trin5=avg(br.map(x=>x.trin),5);
 const highs=num(b.new_highs_52w),lows=num(b.new_lows_52w),issues=(num(b.advancers)||0)+(num(b.decliners)||0)+(num(b.unchanged)||0),lowShare=issues?100*lows/issues:null;
 const breadthVals=[5,20,50,200].map(k=>[k,num(b[`above_${k}d`])]),b5=breadthVals[0][1],b5Pct=percentile(br,'above_5d',b5);
 const vx=num(ctx.vix?.value),v3=num(risk.vix3m),ratio=num(risk.vix_vix3m_ratio),vvix=num(risk.vvix),skew=num(risk.skew),vxPct=percentile(market,'vix',vx),vvPct=num(risk.vvix_percentile_252d),skPct=num(risk.skew_percentile_252d);
 return [
 {id:'cpce',name:'CPCE',desc:'Equity-options fear / greed',value:'—',context:'Feed validation required',status:'unavailable',meaning:'The exact StockCharts $CPCE-equivalent series is not yet verified, so Market Pulse will not display a substitute value.',metrics:['Daily reading','5-day average','1-year percentile'],study:null,historyReason:'Exact historical CPCE feed still requires validation.',source:'Exact source pending validation'},
 {id:'namo',name:'NAMO',desc:'Nasdaq breadth washout / thrust',value:namo==null?'—':namo.toFixed(0),context:namo==null?'Verified feed unavailable':ordinal(namoPct),status:namo==null?'unavailable':statusFromPct(namoPct,namo>=0),meaning:'Measures the momentum of Nasdaq breadth. Deep negative extremes can identify washouts; sharp reversals can identify breadth thrusts.',metrics:['Daily reading','1-year percentile','Thrust detection'],study:null,historyReason:'Exact ratio-adjusted Nasdaq McClellan history is not yet verified.',source:m.namo?.source||'Exact ratio-adjusted EOD source pending'},
 {id:'nymo',name:'NYMO',desc:'Broad-market breadth momentum',value:nymo==null?'—':nymo.toFixed(0),context:nymo==null?'Verified feed unavailable':ordinal(nymoPct),status:nymo==null?'unavailable':statusFromPct(nymoPct,nymo>=0),meaning:'NYSE breadth momentum confirms whether stress or recovery is broad beyond Nasdaq.',metrics:['Daily reading','1-year percentile','Thrust detection'],study:null,historyReason:'Exact ratio-adjusted NYSE McClellan history is not yet verified.',source:m.nymo?.source||'Exact ratio-adjusted EOD source pending'},
 {id:'trin',name:'TRIN / TRINQ',desc:'Capitulation pressure',value:trin==null?'—':trin.toFixed(2),context:trin==null?'Unavailable':ordinal(trinPct),status:trin==null?'unavailable':statusFromPct(trinPct,true),meaning:'Combines issue breadth and volume breadth. High extremes can reveal panic-like selling intensity.',metrics:[`5-day avg ${trin5==null?'—':trin5.toFixed(2)}`,'1-year percentile','TRINQ feed pending'],study:studies.trin,historyReason:'Recorded TRIN history is too short for a study.',source:b.trin_method||'Arms formula'},
 {id:'newlows',name:'New High / New Low Pressure',desc:'Structural internal damage',value:lows==null?'—':`${lows} lows`,context:highs==null?'Current history unavailable':`${highs} highs · ${lowShare==null?'—':lowShare.toFixed(1)+'%'} of issues at new lows`,status:lowShare==null?'unavailable':lowShare>=10?'severe':lowShare>=5?'extreme':'normal',meaning:'Expanding 52-week lows help separate an ordinary pullback from spreading structural damage beneath the indexes.',metrics:['% new lows','High-Low pressure','1-year percentile when history exists'],study:null,historyReason:'Daily new-high/new-low history is not yet stored deeply enough for a trustworthy study.',source:'S&P 500 constituent 52-week highs/lows'},
 {id:'breadth',name:'Breadth Participation',desc:'How many stocks are participating',value:b5==null?'—':`${b5.toFixed(0)}%`,context:b5==null?'Unavailable':`5-day breadth · ${ordinal(b5Pct)}`,status:b5==null?'unavailable':statusFromPct(b5Pct,false),meaning:'Tracks participation across short, intermediate and long trends so index strength can be judged by how many stocks actually support it.',metrics:breadthVals.map(([k,v])=>`${k}d ${v==null?'—':v.toFixed(0)+'%'}`),study:studies.breadth,historyReason:'Recorded breadth history is too short for a study.',source:b.source||'S&P 500 constituent breadth'},
 {id:'vol',name:'Volatility Stress',desc:'Fear urgency / tail risk',value:vx==null?'—':`VIX ${vx.toFixed(1)}`,context:ratio==null?ordinal(vxPct):`${risk.term_structure||'Term structure'} · ratio ${ratio.toFixed(2)}`,status:vx==null?'unavailable':(ratio!=null&&ratio>1)||(vvPct!=null&&vvPct>=90)?'extreme':statusFromPct(vxPct,true),meaning:'Combines VIX term structure, VVIX and SKEW so ordinary volatility is separated from urgent fear and tail-risk demand.',metrics:[`VIX3M ${v3==null?'—':v3.toFixed(1)}`,`VVIX ${vvix==null?'—':vvix.toFixed(1)}${vvPct==null?'':` · ${Math.round(vvPct)}th pct`}`,`SKEW ${skew==null?'—':skew.toFixed(0)}${skPct==null?'':` · ${Math.round(skPct)}th pct`}`],study:studies.vol,historyReason:'Recorded VIX history is too short for a study.',source:risk.source||ctx.vix?.source||'Cboe volatility indices'}
 ]}
function card(s,i){const has=!!s.study;return `<article class="signal-card ${i<2?'primary ':''}${s.status}"><div class="card-head"><div><div class="signal-name">${esc(s.name)}</div><div class="context">${esc(s.desc)}</div></div><span class="status ${s.status}">${s.status==='normal'?'Normal':s.status==='unavailable'?'Unavailable':s.status==='severe'?'Severe extreme':'Extreme'}</span></div><div class="reading">${esc(s.value)}</div><div class="context">${esc(s.context)}</div><p class="meaning">${esc(s.meaning)}</p><div class="submetrics">${s.metrics.map(x=>`<span class="submetric">${esc(x)}</span>`).join('')}</div><div class="card-actions"><button class="study-btn" data-signal="${s.id}" ${has?'':'disabled'}>${has?'Historical study ›':'Historical study unavailable'}</button><span class="source">${esc(s.source)}</span></div>${!has?`<div class="history-reason">${esc(s.historyReason)}</div>`:''}</article>`}
function openHistory(signal){const s=window.__signals.find(x=>x.id===signal),study=s?.study;if(!study)return;const hs=[5,10,21,60].map(k=>[k,study.horizons[k]]).filter(x=>x[1]);$('historyContent').innerHTML=`<div class="kicker">HISTORICAL OUTCOMES</div><h2 class="history-title">${esc(s.name)}</h2><p class="history-intro">${esc(study.rule)} Results use the recorded Market Pulse history available today and SPY forward returns. Historical context only, not a forecast.</p><div class="history-grid">${hs.map(([k,x])=>`<div class="history-stat"><span>${k} DAYS</span><strong>${fmtReturn(x.median)}</strong><small>${Math.round(x.positive_rate)}% positive · n=${x.n}</small><small>Avg ${fmtReturn(x.average)} · Best ${fmtReturn(x.best)} · Worst ${fmtReturn(x.worst)}</small></div>`).join('')}</div><div class="history-note"><strong>Prior matching dates:</strong> ${study.prior_dates.length?study.prior_dates.join(' · '):'Unavailable'}<br><br>Threshold: ${study.high?'top':'bottom'} decile of the recorded series. Sample depth grows as Market Pulse records more closes.</div>`;$('historyPanel').hidden=false;document.body.style.overflow='hidden'}
async function load(){try{const t=Date.now(),[c,h]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!c.ok||!h.ok)throw Error('market data unavailable');const ctx=await c.json(),hist=await h.json(),studies=studiesFromHistory(hist),signals=makeSignals(ctx,hist,studies);window.__signals=signals;$('signalBoard').innerHTML=signals.map(card).join('');const count=signals.filter(x=>x.status==='extreme'||x.status==='severe').length;$('extremeCount').textContent=count;$('heroSummary').textContent=count?`${count} of the seven signal families are currently stretched enough to deserve attention. The board separates true extremes from normal readings and feeds still awaiting validation.`:'None of the verified signals currently qualifies as an extreme. All seven remain visible so you can see what is normal, unavailable, or waiting for confirmation.';$('asOf').textContent=`Latest confirmed close · ${ctx.market_date||'—'}`;document.querySelectorAll('.study-btn[data-signal]').forEach(b=>b.addEventListener('click',()=>openHistory(b.dataset.signal)))}catch(err){$('signalBoard').innerHTML='<article class="signal-card unavailable"><div class="signal-name">Data unavailable</div><p class="meaning">Market Pulse could not load the latest signal data.</p></article>';console.warn(err)}}
$('historyClose').addEventListener('click',()=>{$('historyPanel').hidden=true;document.body.style.overflow=''});$('historyPanel').addEventListener('click',e=>{if(e.target===$('historyPanel'))$('historyClose').click()});$('refresh').addEventListener('click',load);load();
})();
