(()=>{
const $=id=>document.getElementById(id),num=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(rows,key,value)=>{const xs=(rows||[]).map(r=>num(r?.[key])).filter(v=>v!=null).slice(-252);if(value==null||xs.length<20)return null;return 100*xs.filter(v=>v<=value).length/xs.length};
const avg=(xs,n=5)=>{const a=(xs||[]).slice(-n).map(num).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};
const ordinal=p=>p==null?'Percentile unavailable':`${Math.round(p)}${[11,12,13].includes(Math.round(p)%100)?'th':({1:'st',2:'nd',3:'rd'}[Math.round(p)%10]||'th')} percentile`;
const statusFromPct=(p,high=true)=>{if(p==null)return'normal';if(high&&p>=97.5||!high&&p<=2.5)return'severe';if(high&&p>=90||!high&&p<=10)return'extreme';return'normal'};
function studyMatch(studies,terms){const ts=terms.map(x=>x.toLowerCase());return (studies||[]).filter(s=>{const hay=`${s.signal_id||''} ${s.title||''} ${s.category||''} ${s.definition?.rule||''}`.toLowerCase();return ts.some(t=>hay.includes(t))})}
function makeSignals(ctx,hist,studyData){const b=ctx.breadth||{},br=hist.breadth||[],pc=ctx.equity_put_call||{},pcr=hist.put_call||[],m=ctx.mcclellan||{},risk=ctx.options_risk||{},orows=hist.options_risk||[],market=hist.market||[],studies=studyData.studies||[];
 const cpceVal=null; // exact $CPCE-compatible feed is intentionally not trusted yet
 const cpceStudies=[];
 const namo=num(m.namo?.value),namoPct=num(m.namo?.percentile_252d),nymo=num(m.nymo?.value),nymoPct=num(m.nymo?.percentile_252d);
 const trin=num(b.trin),trinPct=pct(br,'trin',trin),trin5=avg(br.map(x=>x.trin),5);
 const highs=num(b.new_highs_52w),lows=num(b.new_lows_52w),issues=(num(b.advancers)||0)+(num(b.decliners)||0)+(num(b.unchanged)||0),lowShare=issues?100*lows/issues:null;
 const breadthVals=[5,20,50,200].map(k=>[k,num(b[`above_${k}d`])]);const b5=breadthVals[0][1],b5Pct=pct(br,'above_5d',b5);
 const vx=num(ctx.vix?.value),v3=num(risk.vix3m),ratio=num(risk.vix_vix3m_ratio),vvix=num(risk.vvix),skew=num(risk.skew),vxPct=pct(market,'vix',vx),vvPct=num(risk.vvix_percentile_252d),skPct=num(risk.skew_percentile_252d);
 return [
 {id:'cpce',name:'CPCE',desc:'Equity-options fear / greed',value:'—',context:'Feed validation required',status:'unavailable',meaning:'The exact StockCharts $CPCE-equivalent series is not yet verified, so Market Pulse will not display a substitute value.',metrics:['Daily','5-day average','1-year percentile'],studies:cpceStudies,source:'Exact source pending validation'},
 {id:'namo',name:'NAMO',desc:'Nasdaq breadth washout / thrust',value:namo==null?'—':namo.toFixed(0),context:namo==null?'Verified feed unavailable':ordinal(namoPct),status:namo==null?'unavailable':statusFromPct(namoPct,namo>=0),meaning:'Measures the momentum of Nasdaq breadth. Deep negative extremes can identify washouts; sharp reversals can identify breadth thrusts.',metrics:['Daily','1-year percentile','Thrust detection'],studies:studyMatch(studies,['namo','nasdaq mcclellan']),source:m.namo?.source||'Exact ratio-adjusted EOD source pending'},
 {id:'nymo',name:'NYMO',desc:'Broad-market breadth momentum',value:nymo==null?'—':nymo.toFixed(0),context:nymo==null?'Verified feed unavailable':ordinal(nymoPct),status:nymo==null?'unavailable':statusFromPct(nymoPct,nymo>=0),meaning:'NYSE breadth momentum confirms whether stress or recovery is broad beyond Nasdaq.',metrics:['Daily','1-year percentile','Thrust detection'],studies:studyMatch(studies,['nymo','nyse mcclellan']),source:m.nymo?.source||'Exact ratio-adjusted EOD source pending'},
 {id:'trin',name:'TRIN / TRINQ',desc:'Capitulation pressure',value:trin==null?'—':trin.toFixed(2),context:trin==null?'Unavailable':ordinal(trinPct),status:trin==null?'unavailable':statusFromPct(trinPct,true),meaning:'Combines issue breadth and volume breadth. High extremes can reveal panic-like selling intensity.',metrics:[`5-day avg ${trin5==null?'—':trin5.toFixed(2)}`,'1-year percentile','TRINQ feed pending'],studies:studyMatch(studies,['trin','arms']),source:b.trin_method||'Arms formula'},
 {id:'newlows',name:'New High / New Low Pressure',desc:'Structural internal damage',value:lows==null?'—':`${lows} lows`,context:highs==null?'Current history unavailable':`${highs} highs · ${lowShare==null?'—':lowShare.toFixed(1)+'%'} of issues at new lows`,status:lowShare==null?'unavailable':lowShare>=10?'severe':lowShare>=5?'extreme':'normal',meaning:'Expanding 52-week lows help separate an ordinary pullback from spreading structural damage beneath the indexes.',metrics:['% new lows','High-Low pressure','1-year percentile when history exists'],studies:studyMatch(studies,['new low','high-low','52-week low']),source:'S&P 500 constituent 52-week highs/lows'},
 {id:'breadth',name:'Breadth Participation',desc:'How many stocks are participating',value:b5==null?'—':`${b5.toFixed(0)}%`,context:b5==null?'Unavailable':`5-day breadth · ${ordinal(b5Pct)}`,status:b5==null?'unavailable':statusFromPct(b5Pct,false),meaning:'Tracks participation across short, intermediate and long trends so index strength can be judged by how many stocks actually support it.',metrics:breadthVals.map(([k,v])=>`${k}d ${v==null?'—':v.toFixed(0)+'%'}`),studies:studyMatch(studies,['breadth','participation']),source:b.source||'S&P 500 constituent breadth'},
 {id:'vol',name:'Volatility Stress',desc:'Fear urgency / tail risk',value:vx==null?'—':`VIX ${vx.toFixed(1)}`,context:ratio==null?ordinal(vxPct):`${risk.term_structure||'Term structure'} · ratio ${ratio.toFixed(2)}`,status:vx==null?'unavailable':(ratio!=null&&ratio>1)||(vvPct!=null&&vvPct>=90)?'extreme':statusFromPct(vxPct,true),meaning:'Combines VIX term structure, VVIX and SKEW so ordinary volatility is separated from urgent fear and tail-risk demand.',metrics:[`VIX3M ${v3==null?'—':v3.toFixed(1)}`,`VVIX ${vvix==null?'—':vvix.toFixed(1)}${vvPct==null?'':` · ${Math.round(vvPct)}th pct`}`,`SKEW ${skew==null?'—':skew.toFixed(0)}${skPct==null?'':` · ${Math.round(skPct)}th pct`}`],studies:studyMatch(studies,['vix','vvix','skew','term structure']),source:risk.source||ctx.vix?.source||'Cboe volatility indices'}
 ]}
function card(s,i){const study=s.studies?.[0],studyText=study?'Historical study available':'Historical study unavailable';return `<article class="signal-card ${i<2?'primary ':''}${s.status}"><div class="card-head"><div><div class="signal-name">${esc(s.name)}</div><div class="context">${esc(s.desc)}</div></div><span class="status ${s.status}">${s.status==='normal'?'Normal':s.status==='unavailable'?'Unavailable':s.status==='severe'?'Severe extreme':'Extreme'}</span></div><div class="reading">${esc(s.value)}</div><div class="context">${esc(s.context)}</div><p class="meaning">${esc(s.meaning)}</p><div class="submetrics">${s.metrics.map(x=>`<span class="submetric">${esc(x)}</span>`).join('')}</div><div class="card-actions"><button class="study-btn" data-signal="${s.id}" ${study?'':'disabled'}>${studyText} ${study?'›':''}</button><span class="source">${esc(s.source)}</span></div></article>`}
function horizon(study,k){return study?.horizons?.[String(k)]?.signal||null}
function openHistory(signal){const s=window.__signals.find(x=>x.id===signal),study=s?.studies?.[0];if(!study)return;const hs=[5,10,21,60,63].map(k=>[k,horizon(study,k)]).filter(x=>x[1]&&num(x[1].n)>0);$('historyContent').innerHTML=`<div class="kicker">HISTORICAL OUTCOMES</div><h2 class="history-title">${esc(s.name)}</h2><p class="history-intro">${esc(study.title||study.definition?.rule||'Comparable historical setup')}. Historical context only, not a forecast.</p><div class="history-grid">${hs.map(([k,x])=>`<div class="history-stat"><span>${k} DAYS</span><strong>${x.median==null?'—':`${Number(x.median)>=0?'+':''}${Number(x.median).toFixed(1)}%`}</strong><small>${x.positive_rate==null?'—':Math.round(x.positive_rate)+'%'} positive · n=${x.n}</small></div>`).join('')}</div><div class="history-note">Average, median, hit rate, sample size, best/worst and prior dates are shown only when supplied by the validated study record.</div>`;$('historyPanel').hidden=false;document.body.style.overflow='hidden'}
async function load(){try{const t=Date.now(),[c,h,e]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'}),fetch(`data/extreme_studies.json?v=${t}`,{cache:'no-store'})]);if(!c.ok||!h.ok)throw Error('market data unavailable');const ctx=await c.json(),hist=await h.json(),studies=e.ok?await e.json():{studies:[]},signals=makeSignals(ctx,hist,studies);window.__signals=signals;$('signalBoard').innerHTML=signals.map(card).join('');const count=signals.filter(x=>x.status==='extreme'||x.status==='severe').length;$('extremeCount').textContent=count;$('heroSummary').textContent=count?`${count} of the seven signal families are currently stretched enough to deserve attention. The board below separates true extremes from normal readings and unavailable feeds.`:'None of the verified signals currently qualifies as an extreme. All seven remain visible so you can see what is normal, unavailable, or waiting for confirmation.';$('asOf').textContent=`Latest confirmed close · ${ctx.market_date||'—'}`;document.querySelectorAll('.study-btn[data-signal]').forEach(b=>b.addEventListener('click',()=>openHistory(b.dataset.signal)))}catch(err){$('signalBoard').innerHTML='<article class="signal-card unavailable"><div class="signal-name">Data unavailable</div><p class="meaning">Market Pulse could not load the latest signal data.</p></article>';console.warn(err)}}
$('historyClose').addEventListener('click',()=>{$('historyPanel').hidden=true;document.body.style.overflow=''});$('historyPanel').addEventListener('click',e=>{if(e.target===$('historyPanel'))$('historyClose').click()});$('refresh').addEventListener('click',load);load();
})();
