(()=>{
const $=id=>document.getElementById(id);
const n=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const pct=(v,d=1)=>n(v)==null?'—':`${n(v)>=0?'+':''}${n(v).toFixed(d)}%`;
const val=(v,d=1)=>n(v)==null?'—':n(v).toFixed(d);
function previousBefore(rows,date){return[...(rows||[])].filter(r=>r?.date&&r.date<date).sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||null}
function card(label,value,copy){return `<article><span>${label}</span><strong>${value}</strong><small>${copy}</small></article>`}
function detail(id,summary,html){let el=$(id);if(!el){el=document.createElement('details');el.id=id;el.className='chapter-explore';el.innerHTML=`<summary>${summary}</summary><div class="chapter-explore-body"></div>`}el.querySelector('.chapter-explore-body').innerHTML=html;return el}
function insertAfter(node,ref){if(node&&ref&&node.parentNode!==ref.parentNode||node&&ref&&node.previousElementSibling!==ref)ref?.after(node)}
function chapter1(d){const snap=$('retailSnapshot');if(!snap)return;const spy=d.etfs?.SPY||{},b=d.breadth||{};const el=detail('chapter1Explore','Explore trend & setup details',`<p class="chapter-explore-intro">The headline view separates long-term market structure from short-term participation so one weak day does not automatically become a bearish regime call.</p><div class="chapter-evidence-grid">${card('SPY VS 20-DAY',pct(spy.distance_ma20),'Short-term trend position')}${card('SPY VS 50-DAY',pct(spy.distance_ma50),'Intermediate trend position')}${card('SPY VS 200-DAY',pct(spy.distance_ma200),'Long-term trend position')}${card('200-DAY BREADTH',n(b.above_200d)==null?'—':`${n(b.above_200d).toFixed(0)}%`,'Long-term participation')}</div><div class="chapter-explain-list"><article><strong>Primary trend</strong><span>Answers whether the broad market structure is still intact.</span></article><article><strong>Short-term condition</strong><span>Shows whether participation is healthy, soft, weakening or washed out right now.</span></article><article><strong>Swing setup</strong><span>Looks for evidence that weakness is becoming a tradable reversal setup rather than simply assuming oversold means bottom.</span></article></div>`);insertAfter(el,snap)}
function chapter2(d,h){const sec=document.querySelector('.intelligence-section');if(!sec)return;const pb=previousBefore(h?.breadth,d.market_date),pm=previousBefore(h?.market,d.market_date);const b=d.breadth||{},spy=d.etfs?.SPY||{};const delta=(a,p,suffix='%')=>n(a)==null||n(p)==null?'—':`${n(a)-n(p)>=0?'+':''}${(n(a)-n(p)).toFixed(1)}${suffix}`;const el=detail('chapter2Explore','Explore close-to-close changes',`<p class="chapter-explore-intro">These comparisons show what actually changed from the prior confirmed close. Small moves are context, not a new market thesis.</p><div class="chapter-evidence-grid">${card('5-DAY BREADTH CHANGE',delta(b.above_5d,pb?.above_5d),'Change in short-term participation')}${card('50-DAY BREADTH CHANGE',delta(b.above_50d,pb?.above_50d),'Change in intermediate participation')}${card('VIX CHANGE',delta(d.vix?.value,pm?.vix,''),'Change in market fear')}${card('SPY DAILY MOVE',pct(spy.change_pct),'Latest confirmed session')}</div>`);const anchor=$('retailChangeSummary')||sec.querySelector('.intelligence-heading');anchor?.after(el)}
function chapter3(d){const bc=$('breadthCycle');if(!bc)return;const b=d.breadth||{},cycle=d.breadth_cycle||{};const momentum=cycle.direction||cycle.state||'Unavailable';const el=detail('chapter3Explore','Explore breadth & stress evidence',`<p class="chapter-explore-intro">The turn sequence is intentionally simple. These are the supporting internals used to decide whether selling is merely broadening, becoming extreme, stabilizing or actually confirming a recovery.</p><div class="chapter-evidence-grid">${card('ADVANCE / DECLINE',val(b.ad_ratio,2),'Stocks rising relative to stocks falling')}${card('OVERSOLD STOCKS',n(b.rsi_below_30_pct)==null?'—':`${n(b.rsi_below_30_pct).toFixed(1)}%`,'S&P 500 stocks with RSI below 30')}${card('TRIN',val(b.trin,2),'Selling-volume pressure')}${card('BREADTH MOMENTUM',String(momentum).replaceAll('_',' '),'McClellan-style S&P 500 breadth momentum')}</div><div class="chapter-explain-list"><article><strong>Washout is not a bottom call</strong><span>Extreme breadth only says selling has become unusually broad. Buyers still need to return.</span></article><article><strong>Confirmation comes last</strong><span>Breadth improvement is stronger when price also repairs short-term trend support.</span></article></div>`);const anchor=$('retailTurnSequence')||bc.querySelector('.bc-head');anchor?.after(el)}
function chapter4(d){const sec=$('historicalForwardReturns');if(!sec)return;const count=sec.querySelectorAll('.close-event-card').length;const el=detail('chapter4Explore','Explore historical methodology',`<p class="chapter-explore-intro">Market Pulse automatically selects the most relevant conditions confirmed at the latest close. You do not need to choose a signal from a dropdown.</p><div class="chapter-evidence-grid">${card('CURRENT SETUPS',count||'—','Automatically selected from the latest confirmed close')}${card('5 DAYS','Forward','Short tactical horizon')}${card('10 DAYS','Forward','Intermediate tactical horizon')}${card('21 DAYS','Forward','About one trading month')}</div><div class="chapter-explain-list"><article><strong>How to read the cards</strong><span>Focus on median return, percent of historical cases that finished higher, sample size and typical additional downside.</span></article><article><strong>Historical context, not a forecast</strong><span>Similar conditions can still produce very different outcomes. Small samples should be treated as low-confidence evidence.</span></article><article><strong>More detail is already inside each event</strong><span>Use “Method & deeper stats” on any event card for its 1-day result, diagnostics and study notes.</span></article></div>`);sec.appendChild(el)}
async function boot(){try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!dr.ok)return;const d=await dr.json(),h=hr.ok?await hr.json():{};const run=()=>{chapter1(d);chapter2(d,h);chapter3(d);chapter4(d)};[350,900,1700,3000,5000].forEach(ms=>setTimeout(run,ms))}catch(e){console.warn('Section details:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();$('refresh')?.addEventListener('click',()=>setTimeout(boot,1700));
})();
