(()=>{
const $=id=>document.getElementById(id);
const n=v=>{if(v==null||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null};
const f=(v,d=2)=>n(v)==null?'—':n(v).toFixed(d);
const pct=(v,d=1)=>n(v)==null?'—':n(v).toFixed(d)+'%';

function risk(d){const o=d.options_risk||{};return{term:n(o.vix_vix3m_ratio),vvix:n(o.vvix_percentile_252d),pc:n(d.equity_put_call?.percentile_60d),skew:n(o.skew_percentile_252d)}}
function stressed(x){return (x.term!=null&&x.term>=.95)&&((x.vvix!=null&&x.vvix>=75)||(x.pc!=null&&x.pc>=75)||(x.skew!=null&&x.skew>=75))}
function acute(x){return (x.term!=null&&x.term>1)||((x.vvix!=null&&x.vvix>=90)&&(x.pc!=null&&x.pc>=75))}

window.regime=function(d){
 const b=d.breadth||{},spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},x=risk(d);const b5=n(b.above_5d),b50=n(b.above_50d),b200=n(b.above_200d),s20=n(spy.distance_ma20),q20=n(qqq.distance_ma20),s50=n(spy.distance_ma50),q50=n(qqq.distance_ma50),s200=n(spy.distance_ma200),q200=n(qqq.distance_ma200);
 const primary=b200!=null&&s200!=null&&q200!=null&&b200>=60&&s200>=0&&q200>=0;const structural=(b200!=null&&b200<40)||((s200!=null&&s200<0)&&(q200!=null&&q200<0));const pressure=(b50!=null&&b50<40)||(s50!=null&&s50<0)||(q50!=null&&q50<0);
 if(structural&&stressed(x))return{name:'Risk-off / structural weakness',tone:'bad',why:'The primary trend is damaged and options-risk structure is confirming elevated stress.'};
 if(structural)return{name:'Primary trend damage',tone:'bad',why:'Long-term trend evidence has deteriorated. Price and participation need to repair before the market can be treated as healthy.'};
 if(b5!=null&&b5<15&&acute(x))return{name:'Broad washout',tone:'bad',why:'Short-term participation is extremely compressed while options-risk pricing is acute. This is genuine capitulation territory, not ordinary weakness.'};
 if(b5!=null&&b5<25&&primary)return{name:'Washout developing',tone:'warn',why:'Selling is unusually broad, but the primary trend remains intact. Confirmation now depends on stabilization and risk pricing.'};
 if(pressure&&primary)return{name:'Trend deterioration',tone:'warn',why:'The long-term structure remains alive, but intermediate support or participation is weakening enough to deserve attention.'};
 if(primary&&((b5!=null&&b5<45)||(s20!=null&&s20<0)||(q20!=null&&q20<0)))return{name:'Healthy pullback',tone:'good',why:'The primary trend remains intact while short-term participation and momentum have cooled.'};
 if(primary&&b50!=null&&b50<50)return{name:'Narrow / fragile rally',tone:'warn',why:'Headline indexes are holding up better than the broader market. Narrow participation makes the advance more vulnerable.'};
 if(primary)return{name:'Healthy uptrend',tone:'good',why:'Long-term trend and participation remain supportive without broad confirmation of acute options-market stress.'};
 return{name:'Mixed / transitional market',tone:'neutral',why:'Trend, participation and stress signals are not aligned strongly enough to call a clean risk-on or risk-off regime.'};
};

window.tacticalState=function(x){const r=n(x.rsi14),m50=n(x.distance_ma50);if(r!=null&&r<35)return'Oversold';if(r!=null&&r>70)return'Overbought';if(m50!=null&&m50<0)return'Soft';if(r!=null&&r>60)return'Firm';if(r==null&&m50==null)return'Unavailable';return'Neutral'};
window.indexSummary=function(sym,x,d){const r=n(x.rsi14),m50=n(x.distance_ma50),m200=n(x.distance_ma200),hi=n(x.distance_52w_high),q=risk(d);const lead=sym==='QQQ'?'Nasdaq 100':'S&P 500';let a=r!=null&&r<35?'short-term momentum is oversold':r!=null&&r<45?'momentum is soft':r!=null&&r>70?'momentum is overbought':r!=null&&r>60?'momentum is firm':r==null?'momentum data is unavailable':'momentum is neutral';let b=m200!=null&&m200<0?'the primary trend is damaged':m50!=null&&m50<0?'intermediate support is under pressure':m50==null||m200==null?'trend data is incomplete':'intermediate and primary trends remain intact';let c=hi!=null&&hi>-3?'Price remains close to its 52-week high.':hi!=null&&hi>-7?'The pullback remains within a normal range.':hi!=null?'The drawdown is becoming meaningful.':'52-week-high distance is unavailable.';let s=q.term==null?'Options-risk structure is unavailable.':acute(q)?'Options-risk pricing is acute.':stressed(q)?'Options-risk pricing is deteriorating.':'Options-risk structure is not confirming acute stress.';return `${lead}: ${a}; ${b}. ${c} ${s}`};
window.indexWatch=function(x,d){const m50=n(x.distance_ma50),m200=n(x.distance_ma200),b50=n(d.breadth?.above_50d),q=risk(d);if(m200!=null&&m200<0)return'Reclaiming the 200-day average, followed by improving 50-day participation, would be the first meaningful repair signal.';if(m50!=null&&m50<0)return'A sustained reclaim of the 50-day average would improve the setup. A 200-day break would turn it into a primary-trend warning.';if(m50==null||m200==null)return'Trend data is incomplete. Wait for confirmed intermediate and long-term readings.';return `A decisive break below the 50-day average, especially with 50-day participation below 40%${b50!=null&&b50<45?' again':''}${q.term!=null?' and VIX/VIX3M moving toward or above 1':''}, would materially weaken the setup.`};

window.renderHistory=function(d,h){const breadth=h?.breadth||[],oh=h?.options_risk||[],b=d.breadth||{},q=risk(d);const percentile=(v,arr)=>{const a=arr.map(n).filter(x=>x!=null);return v==null||a.length<20?null:100*a.filter(x=>x<=v).length/a.length};const label=p=>p==null?null:Math.round(p)<=10?'bottom 10%':Math.round(p)<=20?'bottom 20%':Math.round(p)>=90?'top 10%':Math.round(p)>=80?'top 20%':`${Math.round(p)}th percentile`;const vals=[['5D participation',n(b.above_5d),breadth.map(x=>x.above_5d)],['50D participation',n(b.above_50d),breadth.map(x=>x.above_50d)],['Fear urgency',q.term,oh.map(x=>x.vix_vix3m_ratio)],['VVIX',q.vvix,oh.map(x=>x.vvix).filter(Boolean)]];const ps=vals.map(([a,v,arr])=>[a,percentile(v,arr)]);const bp=ps[0][1],tp=ps[2][1];let lines=[];if(bp!=null)lines.push(`Short-term participation is in the ${label(bp)} of available history.`);if(tp!=null)lines.push(`Fear urgency is in the ${label(tp)} of its available range.`);$('historyHeadline').textContent=bp!=null&&bp<20?'Short-term participation is unusually weak':q.term!=null&&q.term>=.95?'Fear urgency is unusually elevated':'Conditions are within familiar ranges';$('historyContext').textContent=lines.length?lines.join(' '):'Historical context is still being built from daily observations.';$('percentileStrip').innerHTML=ps.filter(x=>x[1]!=null).map(([a,p])=>`<span class="percentile-pill">${a} · ${label(p)}</span>`).join('')};

window.renderChanges=function(d,h){const items=[],bh=h?.breadth||[],oh=h?.options_risk||[];const prevB=[...bh].reverse().find(x=>x.date!==d.market_date),prevO=[...oh].reverse().find(x=>x.date!==d.market_date);const spy=n(d.etfs?.SPY?.change_pct),qqq=n(d.etfs?.QQQ?.change_pct),diff=spy!=null&&qqq!=null?qqq-spy:null;if(diff!=null&&Math.abs(diff)>=.2)items.push({text:`QQQ ${diff<0?'lagged':'outperformed'} SPY by ${Math.abs(diff).toFixed(2)} percentage points.`,why:'Leadership changed enough to monitor, but it needs participation confirmation.'});const q=risk(d),pr=n(prevO?.vix_vix3m_ratio);if(q.term!=null&&pr!=null&&Math.abs(q.term-pr)>=.02)items.push({text:`Fear urgency ${q.term>pr?'increased':'eased'} to ${q.term.toFixed(2)}×.`,why:q.term>=1?'The volatility curve is inverted, confirming acute near-term stress.':q.term>=.95?'The normal term-structure cushion is becoming thin.':'Term structure remains normal.'});const b5=n(d.breadth?.above_5d),pb5=n(prevB?.above_5d);if(b5!=null&&pb5!=null&&Math.abs(b5-pb5)>=3)items.push({text:`5-day participation ${b5>pb5?'improved':'weakened'} ${Math.abs(b5-pb5).toFixed(1)} points since the prior close.`,why:b5<25?'Participation is now broadly oversold.':b5<45?'Short-term participation is weak.':'Participation remains healthy.'});if(!items.length)items.push({text:'No major cross-market condition changed enough to alter the read.',why:'The market regime remains stable despite day-to-day price noise.'});$('changes').innerHTML=items.slice(0,3).map(x=>`<div class="change-row"><strong>${x.text}</strong><span>Why it matters: ${x.why}</span></div>`).join('')};

window.alignment=function(d){const b=d.breadth||{},spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},tags=[],q=risk(d);const b20=n(b.above_20d),b50=n(b.above_50d),b200=n(b.above_200d),rel=n(d.relative_strength?.qqq_vs_spy_20d),s200=n(spy.distance_ma200),q200=n(qqq.distance_ma200),sHi=n(spy.distance_52w_high),qHi=n(qqq.distance_52w_high);if(b200!=null&&s200!=null&&q200!=null&&b200>=60&&s200>=0&&q200>=0)tags.push(['Primary trend confirmed','good']);if(q.term!=null&&q.term<.95&&(!q.vvix||q.vvix<75))tags.push(['Options risk not confirming weakness','good']);if(b20!=null&&b20<45&&b200!=null&&b200>=60)tags.push(['Short-term participation vs long-term trend','warn']);if(((sHi!=null&&sHi>-3)||(qHi!=null&&qHi>-3))&&b50!=null&&b50<45)tags.push(['Price/participation divergence','warn']);if(rel!=null&&Math.abs(rel)>1&&b50!=null&&b50<50)tags.push(['Narrow leadership risk','warn']);if(stressed(q)&&b50!=null&&b50<40)tags.push(['Risk pricing confirms deterioration','bad']);let headline='Evidence mostly aligned',text='Trend, participation and stress measures are broadly telling the same story.';const bad=tags.filter(x=>x[1]==='bad').length,warn=tags.filter(x=>x[1]==='warn').length;if(bad){headline='Weakness is being confirmed';text='Price, participation and options-risk structure are aligning defensively.'}else if(warn>=2){headline='Important divergences are developing';text='Headline price strength and underlying evidence are not fully aligned.'}else if(warn===1){headline='Mostly confirmed, with one divergence';text='The broader evidence supports the current regime, but one internal measure deserves attention.'}else if([b200,s200,q200].some(x=>x==null)){headline='Core evidence is incomplete';text='One or more primary trend inputs are unavailable.'}$('alignmentHeadline').textContent=headline;$('alignmentText').textContent=text;$('alignmentTags').innerHTML=tags.length?tags.map(([a,t])=>`<span class="alignment-tag ${t}">${a}</span>`).join(''):'<span class="alignment-tag neutral">No confirmed divergence</span>';return{headline,text,tags}};

window.renderBrief=function(d,r,a){const b=d.breadth||{},spy=d.etfs?.SPY||{},qqq=d.etfs?.QQQ||{},q=risk(d),b5=n(b.above_5d),b50=n(b.above_50d),b200=n(b.above_200d),s50=n(spy.distance_ma50),q50=n(qqq.distance_ma50);let signal='Stable read';if(r.tone==='bad')signal='Defensive';else if(r.name.includes('Washout'))signal='Stress watch';else if(a.tags.filter(x=>x[1]==='warn').length>=2)signal='Divergence watch';else if(r.name==='Healthy uptrend')signal='Risk-on';else if(r.name==='Healthy pullback')signal='Pullback watch';$('briefSignal').textContent=signal;let text=`${r.name}. ${r.why}`;if(a.headline.includes('divergence'))text+=` ${a.text}`;$('briefText').textContent=text;const trend=s50==null||q50==null||b200==null?'Trend evidence incomplete':s50>=0&&q50>=0&&b200>=60?'Primary trend intact':s50<0||q50<0?'Intermediate support under pressure':'Trend mixed';const breadth=b5==null?'Short-term participation unavailable':b5<25?'Short-term participation washed out':b50!=null&&b50<40?'Intermediate participation weakening':b5<50?'Short-term participation soft':'Participation healthy';const stress=q.term==null?'Options-risk structure unavailable':acute(q)?'Options risk acute':stressed(q)?'Options risk deteriorating':'Options risk contained';$('briefBullets').innerHTML=[['TREND',trend],['PARTICIPATION',breadth],['STRESS',stress]].map(([k,v])=>`<div class="brief-bullet"><span>${k}</span><strong>${v}</strong></div>`).join('')};

window.whatMatters=function(d,r){const q=risk(d);let head='Watch confirmation, not noise',text='The most important next signal is whether participation and price confirm each other.';if(r.name==='Healthy pullback'){head='Does the pullback stay contained?';text='Watch intermediate support and short-term participation. Stabilization with normal term structure supports the reset thesis; a 50-day break plus fear urgency near or above 1 weakens it.'}else if(r.name.includes('Washout')){head='Look for stabilization';text='A washout becomes constructive only if selling stops broadening, momentum turns up and fear urgency begins normalizing.'}else if(r.name.includes('Trend deterioration')){head='Intermediate support is the battleground';text='The next decision point is whether SPY/QQQ reclaim intermediate support and participation improves, or weakness spreads into the primary trend.'}else if(r.name.includes('Risk-off')||r.name.includes('Primary trend')){head='Repair must happen before risk-on';text='Watch for a 200-day reclaim, stronger long-term participation and normalization in term structure/VVIX.'}else if(r.name==='Healthy uptrend'){head='Watch for narrowing participation';text=`The trend is healthy. The earliest warning would be price holding near highs while 20- and 50-day participation deteriorate${q.term!=null?' and fear urgency rises':''}.`}$('watchHeadline').textContent=head;$('watchNow').textContent=text};

window.renderStress=function(sym,d){const x=d.etfs?.[sym]||{},b=d.breadth||{},q=risk(d);const checks=[['Short-term participation',n(b.above_5d)!=null&&n(b.above_5d)<25,`5-day ${pct(b.above_5d,1)} · trigger <25%`],['20-day participation',n(b.above_20d)!=null&&n(b.above_20d)<35,`20-day ${pct(b.above_20d,1)} · trigger <35%`],['Momentum stretch',n(x.rsi14)!=null&&n(x.rsi14)<35,`RSI ${f(x.rsi14,1)} · trigger <35`],['Fear urgency',q.term!=null&&q.term>=.95,`VIX/VIX3M ${f(q.term,2)}× · trigger ≥0.95`],['Options-risk confirmation',(q.vvix!=null&&q.vvix>=75)||(q.pc!=null&&q.pc>=75),`VVIX ${q.vvix==null?'—':Math.round(q.vvix)+'th pct'} · Put/call ${q.pc==null?'—':Math.round(q.pc)+'th pct'}`]];const hits=checks.filter(x=>x[1]).length;$('stressCount').textContent=`${hits} of ${checks.length}`;$('stressChecklist').innerHTML=checks.map(([a,hit,b])=>`<div class="stress-item ${hit?'hit':''}"><div class="check">${hit?'✓':'–'}</div><strong>${a}</strong><small>${b}</small></div>`).join('');$('stressTake').textContent=hits>=4?'Multiple independent stress signals are aligned. This is a genuine washout environment, not ordinary noise.':hits>=2?'Some tactical stress is present, but confirmation is incomplete.':'Very few washout conditions are present.'};

const CLEAN_ALERTS={breadth25:{name:'Broad washout developing',desc:'5-day S&P participation falls below 25%.',test:d=>n(d.breadth?.above_5d)!=null&&n(d.breadth.above_5d)<25},term:{name:'Fear urgency elevated',desc:'VIX/VIX3M reaches 0.95 or higher.',test:d=>n(d.options_risk?.vix_vix3m_ratio)!=null&&n(d.options_risk.vix_vix3m_ratio)>=.95},vvix:{name:'Volatility uncertainty extreme',desc:'VVIX reaches the top decile of its one-year range.',test:d=>n(d.options_risk?.vvix_percentile_252d)!=null&&n(d.options_risk.vvix_percentile_252d)>=90},spy50:{name:'SPY loses intermediate support',desc:'SPY closes below its 50-day average.',test:d=>n(d.etfs?.SPY?.distance_ma50)!=null&&n(d.etfs.SPY.distance_ma50)<0},structure:{name:'Long-term participation damage',desc:'S&P 500 200-day participation falls below 50%.',test:d=>n(d.breadth?.above_200d)!=null&&n(d.breadth.above_200d)<50}};
window.renderAlerts=function(d){let prefs={};try{prefs={...Object.fromEntries(Object.keys(CLEAN_ALERTS).map(k=>[k,true])),...JSON.parse(localStorage.getItem('marketPulseAlertsV2')||'{}')}}catch{};$('alertsGrid').innerHTML=Object.entries(CLEAN_ALERTS).map(([id,a])=>{const hit=a.test(d),on=prefs[id]!==false;return `<div class="alert-item"><div class="alert-copy"><strong>${a.name}</strong><span>${a.desc}</span><div class="alert-state ${hit?'triggered':'clear'}">${hit?'Triggered now':'Not triggered'}</div></div><label class="switch"><input type="checkbox" data-alert-v2="${id}" ${on?'checked':''}><span class="slider"></span></label></div>`}).join('');$('alertsGrid').querySelectorAll('input[data-alert-v2]').forEach(el=>el.onchange=()=>{prefs[el.dataset.alertV2]=el.checked;localStorage.setItem('marketPulseAlertsV2',JSON.stringify(prefs))})};

window.renderIndex=function(sym,d){const x=d.etfs?.[sym]||{},box=$(sym.toLowerCase()),pr=$(sym.toLowerCase()+'Price'),change=n(x.change_pct);pr.textContent=n(x.price)==null?'--':`$${f(x.price,2)}  ${change==null?'':`${change>=0?'+':''}${pct(change,2)}`}`;box.innerHTML='';let s,t;[s,t]=st('rsi',x.rsi14);box.appendChild(card('rsi','RSI (14)',f(x.rsi14,1),'Short-term momentum stretch.',s,t));const m=n(x.macd),ms=n(x.macd_signal),q=m==null?['Unavailable','neutral']:ms==null?['Positive momentum','good']:m>=ms?['Momentum improving','good']:['Momentum weakening','warn'];box.appendChild(card('macd','MACD',f(m,2),'Trend momentum confirmation.',q[0],q[1]));[s,t]=st('adx',x.adx14);box.appendChild(card('adx','ADX (14)',f(x.adx14,1),'How strong the current trend is.',s,t));for(const h of[50,200]){const k='ma'+h,v=x['distance_ma'+h];[s,t]=st(k,v);box.appendChild(card(k,`Distance from ${h}-day MA`,pct(v,2),h===50?'Intermediate trend.':'Primary trend.',s,t))}const hi=n(x.distance_52w_high),rel=n(d.relative_strength?.qqq_vs_spy_20d);$(sym.toLowerCase()+'Summary').textContent=indexSummary(sym,x,d);$(sym.toLowerCase()+'High').textContent=pct(hi,2);$(sym.toLowerCase()+'Leadership').textContent=rel==null?'—':`${rel>=0?'+':''}${rel.toFixed(2)}%`;$(sym.toLowerCase()+'Tactical').textContent=tacticalState(x);$(sym.toLowerCase()+'Watch').textContent=indexWatch(x,d)};

function cleanVisibleVix(d){document.querySelectorAll('.chip').forEach(el=>{if(/^VIX\s*·/i.test(el.textContent||'')){const r=n(d?.options_risk?.vix_vix3m_ratio);el.textContent=`Fear urgency · ${r==null?'—':r.toFixed(2)+'×'}`}})}

function injectStyles(){if(document.getElementById('contextPlusStyle'))return;const s=document.createElement('style');s.id='contextPlusStyle';s.textContent=`.context-plus{margin-top:18px}.context-plus .module-header{margin-bottom:14px}.context-plus-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.context-plus-card{background:var(--panel,#fff);border:1px solid rgba(120,135,155,.2);border-radius:16px;padding:16px}.context-plus-card .k{font-size:11px;letter-spacing:.12em;font-weight:700;opacity:.65}.context-plus-card .big{font-size:24px;font-weight:800;margin:7px 0}.context-plus-card p{margin:5px 0 0;line-height:1.45}.context-plus-strip{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.context-plus-pill{border:1px solid rgba(120,135,155,.2);border-radius:999px;padding:7px 10px;font-size:12px}.context-plus-note{font-size:12px;opacity:.7;margin-top:12px}@media(max-width:620px){.context-plus-grid{grid-template-columns:1fr}.context-plus-card{padding:14px}.context-plus-card .big{font-size:21px}}`;document.head.appendChild(s)}
function ensureSections(){injectStyles();const anchor=document.querySelector('.shared-context');if(!anchor)return;let sentiment=$('marketSentimentModule');if(!sentiment){sentiment=document.createElement('section');sentiment.id='marketSentimentModule';sentiment.className='module context-plus';sentiment.hidden=true;sentiment.innerHTML=`<div class="module-header"><div><div class="eyebrow">MARKET SENTIMENT</div><h2>Is the crowd becoming euphoric or fearful?</h2><p>Stocktwits sentiment and attention are used only as confirmation or divergence context.</p></div></div><div id="marketSentimentGrid" class="context-plus-grid"></div><p class="context-plus-note">Crowd sentiment is not a standalone trade signal.</p>`;anchor.after(sentiment)}let liq=$('globalLiquidityModule');if(!liq){liq=document.createElement('section');liq.id='globalLiquidityModule';liq.className='module context-plus';liq.hidden=true;liq.innerHTML=`<div class="module-header"><div><div class="eyebrow">GLOBAL LIQUIDITY</div><h2>Is the liquidity backdrop becoming more supportive?</h2><p>A transparent proxy using major central-bank balance sheets and the U.S. dollar.</p></div></div><div id="globalLiquidityGrid" class="context-plus-grid"></div><div id="globalLiquidityComponents" class="context-plus-strip"></div><p id="globalLiquidityNote" class="context-plus-note"></p>`;sentiment.after(liq)}}
function sentimentTone(v){return v>=80?'Extremely bullish':v>=60?'Bullish':v<=20?'Extremely bearish':v<=40?'Bearish':'Neutral'}
async function loadSentiment(){try{const r=await fetch(`data/stocktwits_sentiment.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(d.status!=='ok')return;const host=$('marketSentimentModule'),grid=$('marketSentimentGrid');if(!host||!grid)return;const cards=['SPY','QQQ'].map(sym=>{const x=d.symbols?.[sym]||{},s=n(x.sentiment_score),v=n(x.message_volume_score);return `<article class="context-plus-card"><div class="k">${sym} CROWD SENTIMENT</div><div class="big">${s==null?'—':Math.round(s)+'/100'}</div><strong>${s==null?'Unavailable':sentimentTone(s)}</strong><p>Crowd attention: ${v==null?'unavailable':Math.round(v)+'/100'+(v>=80?' · extreme':v>=60?' · elevated':'')}</p></article>`}).join('');grid.innerHTML=cards;host.hidden=false}catch(e){console.warn('Sentiment:',e)}}
async function loadLiquidity(){try{const r=await fetch(`data/global_liquidity.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(!d.backdrop)return;const host=$('globalLiquidityModule'),grid=$('globalLiquidityGrid'),parts=$('globalLiquidityComponents');if(!host||!grid||!parts)return;grid.innerHTML=`<article class="context-plus-card"><div class="k">LIQUIDITY BACKDROP</div><div class="big">${d.backdrop}</div><strong>Composite ${d.score==null?'—':Number(d.score).toFixed(2)}</strong><p>${d.backdrop==='SUPPORTIVE'?'More components are adding liquidity support than tightening it.':d.backdrop==='UNSUPPORTIVE'?'More components are tightening than supporting risk assets.':'The major components are not aligned strongly enough for a directional liquidity read.'}</p></article><article class="context-plus-card"><div class="k">RATE OF CHANGE</div><div class="big">${d.momentum||'—'}</div><strong>4-week score change ${d.score_change_4w==null?'—':Number(d.score_change_4w).toFixed(2)}</strong><p>Momentum matters more than the absolute level when looking for a changing market backdrop.</p></article>`;parts.innerHTML=(d.components||[]).map(x=>`<span class="context-plus-pill">${x.label}: ${x.change_3m_pct>=0?'+':''}${x.change_3m_pct}% · ${x.contribution}</span>`).join('');$('globalLiquidityNote').textContent=d.limitations||d.methodology||'';host.hidden=false}catch(e){console.warn('Liquidity:',e)}}

ensureSections();loadSentiment();loadLiquidity();
setTimeout(()=>{if(window.currentData)cleanVisibleVix(window.currentData);if(typeof window.load==='function')window.load()},900);
document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(()=>{ensureSections();loadSentiment();loadLiquidity();if(window.currentData)cleanVisibleVix(window.currentData)},1600));
})();
