(()=>{
const $=id=>document.getElementById(id);const n=v=>Number.isFinite(Number(v))?Number(v):null;
function classify(d){return typeof regime==='function'?regime(d):{name:'Market read',tone:'neutral',why:''}}
function leadership(rel){if(rel==null)return'Leadership is balanced.';if(rel>1)return'Growth and technology are leading the broad market. That is constructive while breadth stays healthy, but it becomes a concentration risk if fewer stocks participate.';if(rel<-1)return'The broader market is leading growth and technology. That is usually a healthier form of participation if breadth is improving at the same time.';return'Leadership is balanced between growth and the broader market, so there is no major style imbalance driving the tape.'}
function read(d){const r=classify(d),b=d.breadth||{},s=d.etfs?.SPY||{},q=d.etfs?.QQQ||{},v=n(d.vix?.value),pc=n(d.equity_put_call?.value),rel=n(d.relative_strength?.qqq_vs_spy_20d),b5=n(b.above_5d),b50=n(b.above_50d),b200=n(b.above_200d),s50=n(s.distance_ma50),q50=n(q.distance_ma50),s200=n(s.distance_ma200),q200=n(q.distance_ma200);let what='',why='',watch='';
if(r.name==='Healthy uptrend'){what='The market is still in a healthy uptrend.';why=`The big picture remains constructive${b200!=null?`: ${b200.toFixed(0)}% of S&P 500 stocks are above their 200-day trends`:''}. Price is holding above long-term support and volatility is not signaling broad stress.`;watch='Stay constructive, but watch for narrowing participation. The first real warning would be 20- and 50-day breadth deteriorating while the indexes stay near their highs, especially if VIX starts rising too.'}
else if(r.name==='Healthy pullback'){what='The market is bending, not breaking.';why=`Short-term participation has cooled${b5!=null?` to ${b5.toFixed(0)}% above 5-day trends`:''}, but the long-term structure is still intact. That keeps this in the pullback camp rather than a bearish regime call.`;watch='The tell from here is 50-day participation. If breadth stabilizes and the indexes hold or reclaim their 50-day trends, the reset remains healthy. If breadth keeps deteriorating and VIX moves above 20, the risk profile changes.'}
else if(r.name==='Washout developing'){what='Selling is getting broad enough to matter, but the long-term trend has not broken.';why=`Short-term breadth is compressed${b5!=null?` at ${b5.toFixed(0)}%`:''}. That can set up a sharp reset, but only if selling pressure stops spreading and the longer-term trend remains intact.`;watch='Watch for breadth to stop falling, momentum to turn up, and SPY/QQQ to hold key trend support. A rebound in breadth with contained volatility would be constructive; further deterioration would turn this from opportunity into damage.'}
else if(r.name==='Broad washout'){what='This is no longer ordinary weakness — selling pressure is broad and fear is elevated.';why='When breadth, momentum and volatility all deteriorate together, the market is showing genuine stress. That can eventually create opportunity, but the first job is to see evidence that forced selling is exhausting itself.';watch='Do not treat oversold as a buy signal by itself. Look for breadth to stabilize, VIX to stop rising, and price to reclaim short-term support before calling the washout complete.'}
else if(r.name==='Trend deterioration'){what='The long-term bull structure is still alive, but the market is losing support underneath the surface.';why=`Intermediate participation is weakening${b50!=null?` with 50-day breadth at ${b50.toFixed(0)}%`:''}. That matters because index-level strength can hide deterioration in the average stock for a while.`;watch='The next decision point is simple: either SPY/QQQ reclaim and hold their 50-day trends while breadth improves, or weakness spreads toward the 200-day structure. The second outcome would move this from caution to defense.'}
else if(r.name==='Narrow / fragile rally'){what='The indexes look healthier than the market underneath them.';why='Leadership is concentrated and participation is not broad enough to give the advance a strong foundation. Narrow rallies can continue, but they are more vulnerable to disappointment.';watch='Watch whether 20- and 50-day breadth catches up. If participation broadens, the rally gets healthier. If the indexes stay elevated while breadth falls, the divergence becomes more important.'}
else if(r.name.includes('Risk-off')){what='The market is in a defensive regime.';why='Long-term trend damage is now being confirmed by elevated stress. At that point, oversold readings matter less than whether price and breadth can repair.';watch='The burden of proof shifts to the bulls. Look for a 200-day reclaim, stronger long-term breadth and cooling volatility before treating weakness as repaired.'}
else if(r.name.includes('Primary trend')){what='The long-term trend has been damaged.';why='The market has lost enough structural support that short-term rebounds should be treated as repair attempts, not proof that the weakness is over.';watch='A durable improvement requires price to reclaim long-term trend support and breadth to improve with it. Until then, rallies deserve more skepticism.'}
else{what='The market is sending mixed signals.';why='Trend, breadth and stress are not aligned strongly enough to justify a high-confidence bullish or bearish call.';watch='Wait for confirmation. Improving breadth with contained volatility would strengthen the bullish case; weakening trend support with rising stress would strengthen the bearish one.'}
return{r,what,why,watch,lead:leadership(rel),stats:{b5,b50,b200,v,pc,rel,s50,q50,s200,q200}}}
function indexCopy(sym,x,d){const name=sym==='SPY'?'S&P 500':'Nasdaq 100',m50=n(x.distance_ma50),m200=n(x.distance_ma200),hi=n(x.distance_52w_high),rsi=n(x.rsi14),v=n(d.vix?.value);let trend=m200!=null&&m200<0?'has broken its long-term trend':m50!=null&&m50<0?'is below its 50-day trend but still above long-term support':'remains above both intermediate and long-term trend support';let stretch=rsi!=null&&rsi<35?'Momentum is oversold, which raises rebound potential but does not guarantee a bottom.':rsi!=null&&rsi>65?'Momentum is firm, though strong readings can become stretched.':'Momentum is neither stretched nor signaling panic.';let depth=hi!=null&&hi>-3?'It is still trading close to its 52-week high.':hi!=null&&hi>-7?'The pullback remains within a normal range.':'The drawdown is deep enough to deserve more attention.';let stress=v!=null&&v<20?'Volatility is still contained.':'Volatility is elevated, so downside moves carry more weight.';return `${name} ${trend}. ${depth} ${stretch} ${stress}`}
function indexWatch(sym,x,d){const m50=n(x.distance_ma50),m200=n(x.distance_ma200),b50=n(d.breadth?.above_50d),v=n(d.vix?.value);if(m200!=null&&m200<0)return `The repair signal is a sustained reclaim of the 200-day trend, ideally with 50-day breadth improving at the same time. Until that happens, rebounds are repair attempts rather than a confirmed trend change.`;if(m50!=null&&m50<0)return `A reclaim of the 50-day trend would improve the setup. A failure to reclaim it — especially with 50-day breadth below 40%${v!=null&&v>=20?' and VIX already above 20':''} — would increase the odds that weakness is spreading.`;return `The 50-day trend is the first line to watch. A clean break below it matters much more if 50-day breadth also falls below 40% and VIX pushes above 20. Without that confirmation, ordinary pullbacks should not be mistaken for regime changes.`}
function apply(d){const x=read(d);if($('summary'))$('summary').textContent=`${x.what} ${x.why}`;if($('briefText'))$('briefText').textContent=`${x.what} ${x.why} ${x.lead}`;if($('watchHeadline'))$('watchHeadline').textContent=x.r.name==='Healthy uptrend'?'Watch participation beneath the indexes':x.r.name==='Healthy pullback'?'The 50-day trend is the battleground':x.r.name.includes('Washout')?'Look for evidence selling is exhausting itself':x.r.name==='Trend deterioration'?'Can the market repair intermediate support?':x.r.name.includes('Risk-off')||x.r.name.includes('Primary trend')?'The bulls need to prove repair':'Wait for the market to resolve the conflict';if($('watchNow'))$('watchNow').textContent=x.watch;for(const sym of['SPY','QQQ']){const e=d.etfs?.[sym]||{};const id=sym.toLowerCase();if($(id+'Summary'))$(id+'Summary').textContent=indexCopy(sym,e,d);if($(id+'Watch'))$(id+'Watch').textContent=indexWatch(sym,e,d)}if($('stressTake')){const b=d.breadth||{},hits=[n(b.above_5d)<25,n(b.above_20d)<35,(n(d.etfs?.SPY?.rsi14)<35||n(d.etfs?.SPY?.williams_r14)<-80),n(d.vix?.value)>=20,n(d.equity_put_call?.value)>=.9].filter(Boolean).length;$('stressTake').textContent=hits>=4?'Stress is broad and synchronized. This is a genuine washout environment, but oversold conditions are not the same as a confirmed bottom — stabilization still matters.':hits>=2?'There is meaningful short-term stress, but the evidence is not yet synchronized enough to call capitulation. That keeps this in watch mode rather than panic mode.':'The market is not showing broad capitulation. Weakness may be uncomfortable, but the stress evidence remains limited.'}}
async function boot(){try{const r=await fetch(`data/market_context.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();apply(d);setTimeout(()=>apply(d),650);setTimeout(()=>apply(d),1400)}catch(e){console.warn('Strategist commentary:',e)}}
window.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100));document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(boot,800));
})();
