(()=>{
const $=id=>document.getElementById(id);
const n=v=>{if(v==null||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null};
function classify(d){return typeof regime==='function'?regime(d):{name:'Market read',tone:'neutral',why:''}}
function leadership(rel){if(rel==null)return'Leadership is balanced.';if(rel>1)return'Growth and technology are leading the broad market. That is constructive while participation stays healthy, but it becomes a concentration risk if fewer stocks take part.';if(rel<-1)return'The broader market is leading growth and technology. That is usually a healthier form of strength if participation is improving at the same time.';return'Leadership is balanced between growth and the broader market, so there is no major style imbalance driving the tape.'}
function read(d){const r=classify(d),b=d.breadth||{},s=d.etfs?.SPY||{},q=d.etfs?.QQQ||{},v=n(d.vix?.value),rel=n(d.relative_strength?.qqq_vs_spy_20d),b5=n(b.above_5d),b50=n(b.above_50d),b200=n(b.above_200d),s50=n(s.distance_ma50),q50=n(q.distance_ma50),s200=n(s.distance_ma200),q200=n(q.distance_ma200);let what='',why='',watch='';
if(r.name==='Healthy uptrend'){what='The market is still in a healthy uptrend.';why=`The big picture remains constructive${b200!=null?`: ${b200.toFixed(0)}% of S&P 500 stocks are still holding their long-term trends`:''}. The major indexes remain above long-term support and market stress is contained.`;watch='Stay constructive, but watch whether fewer stocks begin carrying the market. The first meaningful warning would be participation weakening while the indexes stay near their highs, especially if volatility rises too.'}
else if(r.name==='Healthy pullback'){what='The market is bending, not breaking.';why=`Short-term participation has cooled${b5!=null?` to ${b5.toFixed(0)}% of S&P 500 stocks holding their one-week trends`:''}, but the long-term structure is still intact. That keeps this in the normal-pullback camp rather than a bearish regime call.`;watch='The key test is intermediate participation. If more stocks stabilize and the indexes hold or reclaim intermediate support, the reset remains healthy. If participation keeps deteriorating and volatility moves above 20, the risk profile changes.'}
else if(r.name==='Washout developing'){what='Selling is getting broad enough to matter, but the long-term trend has not broken.';why=`Short-term participation is compressed${b5!=null?` at ${b5.toFixed(0)}%`:''}. That can create a sharp reset, but only if selling pressure stops spreading and the longer-term trend remains intact.`;watch='Watch for the number of advancing stocks to improve, short-term momentum to turn up, and SPY/QQQ to hold key trend support. Better participation with contained volatility would be constructive; further deterioration would turn this from opportunity into damage.'}
else if(r.name==='Broad washout'){what='This is no longer ordinary weakness - selling is broad and fear is elevated.';why='When participation, short-term momentum and volatility all deteriorate together, the market is showing genuine stress. That can eventually create opportunity, but first we need evidence that forced selling is exhausting itself.';watch='Do not treat “oversold” as a buy signal by itself. Look for more stocks to begin advancing, volatility to stop rising, and price to reclaim short-term support before calling the washout complete.'}
else if(r.name==='Trend deterioration'){what='The long-term bull structure is still alive, but support underneath the market is weakening.';why=`Intermediate participation is deteriorating${b50!=null?`, with only ${b50.toFixed(0)}% of S&P 500 stocks still holding their intermediate trends`:''}. That matters because the headline indexes can look healthy even while the average stock weakens.`;watch='The next decision point is simple: either SPY/QQQ reclaim and hold intermediate support while participation improves, or weakness spreads toward long-term support. The second outcome would move the dashboard from caution toward defense.'}
else if(r.name==='Narrow / fragile rally'){what='The indexes look healthier than the market underneath them.';why='Leadership is concentrated and too few stocks are participating to give the advance a strong foundation. Narrow rallies can continue, but they are more vulnerable to disappointment.';watch='Watch whether participation catches up. If more stocks join the advance, the rally gets healthier. If the indexes stay elevated while participation falls, that divergence becomes more important.'}
else if(r.name.includes('Risk-off')){what='The market is in a defensive regime.';why='Long-term trend damage is now being confirmed by elevated stress. At that point, short-term oversold readings matter less than whether price and participation can repair.';watch='The burden of proof shifts to the bulls. Look for a reclaim of long-term support, broader participation and cooling volatility before treating weakness as repaired.'}
else if(r.name.includes('Primary trend')){what='The long-term trend has been damaged.';why='The market has lost enough structural support that short-term rebounds should be treated as repair attempts, not proof that the weakness is over.';watch='A durable improvement requires the major indexes to reclaim long-term support and more stocks to improve with them. Until then, rallies deserve more skepticism.'}
else{what='The market is sending mixed signals.';why='Trend, participation and stress are not aligned strongly enough to justify a high-confidence bullish or bearish call.';watch='Wait for confirmation. Improving participation with contained volatility would strengthen the bullish case; weakening trend support with rising stress would strengthen the bearish one.'}
return{r,what,why,watch,lead:leadership(rel),stats:{b5,b50,b200,v,rel,s50,q50,s200,q200}}}
function indexCopy(sym,x,d){const name=sym==='SPY'?'S&P 500':'Nasdaq 100',m50=n(x.distance_ma50),m200=n(x.distance_ma200),hi=n(x.distance_52w_high),rsi=n(x.rsi14),v=n(d.vix?.value);let trend=m200!=null&&m200<0?'has broken its long-term trend':m50!=null&&m50<0?'is below intermediate support but still above long-term support':m50==null||m200==null?'has incomplete trend data':'remains above both intermediate and long-term support';let stretch=rsi!=null&&rsi<35?'Short-term momentum is stretched to the downside, which raises rebound potential but does not guarantee a bottom.':rsi!=null&&rsi>65?'Short-term momentum is strong, though the move is becoming stretched.':rsi==null?'Short-term momentum data is unavailable.':'Short-term momentum is neither stretched nor signaling panic.';let depth=hi!=null&&hi>-3?'It is still trading close to its 52-week high.':hi!=null&&hi>-7?'The pullback remains within a normal range.':hi==null?'Distance from the 52-week high is unavailable.':'The drawdown is deep enough to deserve more attention.';let stress=v==null?'Volatility data is unavailable.':v<20?'Market stress is still contained.':'Market stress is elevated, so downside moves carry more weight.';return `${name} ${trend}. ${depth} ${stretch} ${stress}`}
function indexWatch(sym,x,d){const m50=n(x.distance_ma50),m200=n(x.distance_ma200),v=n(d.vix?.value);if(m200!=null&&m200<0)return 'The repair signal is a sustained reclaim of long-term support, ideally with more stocks improving at the same time. Until that happens, rebounds are repair attempts rather than a confirmed trend change.';if(m50!=null&&m50<0)return `A reclaim of intermediate support would improve the setup. A failure to reclaim it - especially if fewer than 40% of S&P 500 stocks hold their intermediate trends${v!=null&&v>=20?' and volatility is already elevated':''} - would increase the odds that weakness is spreading.`;if(m50==null||m200==null)return 'Trend data is incomplete. Wait for confirmed intermediate and long-term readings before drawing a directional conclusion.';return 'Intermediate support is the first line to watch. A clean break below it matters much more if broad participation also falls sharply and volatility rises above 20. Without that confirmation, ordinary pullbacks should not be mistaken for regime changes.'}
function apply(d){const x=read(d);if($('summary'))$('summary').textContent=`${x.what} ${x.why}`;if($('briefText'))$('briefText').textContent=`${x.what} ${x.why} ${x.lead}`;if($('watchHeadline'))$('watchHeadline').textContent=x.r.name==='Healthy uptrend'?'Watch participation beneath the indexes':x.r.name==='Healthy pullback'?'Intermediate support is the battleground':x.r.name.includes('Washout')?'Look for evidence selling is exhausting itself':x.r.name==='Trend deterioration'?'Can the market repair intermediate support?':x.r.name.includes('Risk-off')||x.r.name.includes('Primary trend')?'The bulls need to prove repair':'Wait for the market to resolve the conflict';if($('watchNow'))$('watchNow').textContent=x.watch;for(const sym of['SPY','QQQ']){const e=d.etfs?.[sym]||{},id=sym.toLowerCase();if($(id+'Summary'))$(id+'Summary').textContent=indexCopy(sym,e,d);if($(id+'Watch'))$(id+'Watch').textContent=indexWatch(sym,e,d)}if($('stressTake')){const b=d.breadth||{},b5=n(b.above_5d),b20=n(b.above_20d),spyRsi=n(d.etfs?.SPY?.rsi14),spyWr=n(d.etfs?.SPY?.williams_r14),vix=n(d.vix?.value);const hits=[b5!=null&&b5<25,b20!=null&&b20<35,(spyRsi!=null&&spyRsi<35)||(spyWr!=null&&spyWr<-80),vix!=null&&vix>=20].filter(Boolean).length;$('stressTake').textContent=hits>=3?'Stress is broad and synchronized. This is a genuine washout environment, but stretched conditions are not the same as a confirmed bottom - stabilization still matters.':hits>=2?'There is meaningful short-term stress, but the evidence is not yet synchronized enough to call capitulation. That keeps this in watch mode rather than panic mode.':'The market is not showing broad capitulation. Weakness may be uncomfortable, but the stress evidence remains limited.'}}
async function boot(){try{const r=await fetch(`data/market_context.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();apply(d);setTimeout(()=>apply(d),650);setTimeout(()=>apply(d),1400)}catch(e){console.warn('Strategist commentary:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100));else setTimeout(boot,100);
document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(boot,800));
})();