(()=>{
const $=id=>document.getElementById(id);
const num=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
function priorBreadth(history){const rows=(history?.breadth||[]).filter(x=>num(x?.above_5d)!=null);if(!rows.length)return{prev:null,min10:null};const vals=rows.map(x=>num(x.above_5d));return{prev:vals.length>1?vals[vals.length-2]:null,min10:Math.min(...vals.slice(-10))}}
function classify(d,h){const b=d.breadth||{},b5=num(b.above_5d),ad=num(b.ad_ratio),rsi=num(b.rsi_below_30),trin=num(b.trin),vix=num(d.vix?.value),{prev,min10}=priorBreadth(h);if(b5==null)return{stage:'Unavailable',tone:'neutral',headline:'Tactical participation data is unavailable',copy:'Use the primary market regime until one-week participation (MMFD-style breadth) is available.',watch:'Wait for a confirmed MMFD-style one-week participation reading.',action:'Use the primary regime as the decision anchor.',role:'TACTICAL - DOES NOT OVERRIDE REGIME'};
const recover20=min10!=null&&min10<15&&prev!=null&&prev<=20&&b5>20;
const recover50=min10!=null&&min10<20&&prev!=null&&prev<=50&&b5>50;
const stressCount=[ad!=null&&ad<.7,rsi!=null&&rsi>=20,trin!=null&&trin>=1.3,vix!=null&&vix>=20].filter(Boolean).length;
if(recover50)return{stage:'Recovery confirming',tone:'constructive',headline:'Buyers are returning after broad weakness',copy:`One-week participation (MMFD-style breadth) has rebounded to ${b5.toFixed(0)}% - more than half of S&P 500 stocks are now back above their 5-day average after a recent washout.`,watch:'Hold above 50% participation while intermediate support remains intact. That would keep the breadth recovery confirmed.',action:'The tactical evidence is improving. Favor confirmation over chasing the first rebound.',role:'CONFIRMATION'};
if(recover20)return{stage:'Stabilizing',tone:'constructive',headline:'The first recovery signal has appeared',copy:`One-week participation (MMFD-style breadth) has recovered to ${b5.toFixed(0)}% after fewer than 15% of S&P 500 stocks were above their 5-day average.`,watch:'MMFD-style participation above 50% - more than half of S&P 500 stocks above their 5-day average - would strengthen the turn.',action:'Rebound potential is improving, but wait for broader participation before treating the turn as confirmed.',role:'EARLY RECOVERY'};
if(b5<10)return{stage:'Washout',tone:'stress',headline:'Selling is hitting almost everything',copy:`Only ${b5.toFixed(0)}% of S&P 500 stocks are above their 5-day average - an extreme MMFD-style breadth washout${stressCount?` with ${stressCount} other stress check${stressCount===1?' is':'s are'} elevated`:''}.`,watch:'First improvement: MMFD-style participation back above 20%. Stronger confirmation: above 50%, meaning more than half the index is back above its 5-day average.',action:'Do not confuse extreme weakness with a confirmed low. Rebound potential is high, but buyers still need to return.',role:'TACTICAL EXTREME'};
if(b5<20)return{stage:'Washout developing',tone:'caution',headline:'Short-term selling is becoming extreme',copy:`Only ${b5.toFixed(0)}% of S&P 500 stocks are above their 5-day average. In MMFD-style breadth terms, fewer than 1 in 5 stocks are holding their one-week trend.`,watch:'MMFD below 20% keeps the washout active. A recovery above 20%, then 50%, would show buyers returning across more of the market.',action:'Stay alert for a tactical turn, but do not treat oversold conditions alone as a buy signal.',role:'EXHAUSTION WATCH'};
if(b5<35)return{stage:'Weakening',tone:'caution',headline:'Selling is broad, but not yet a full washout',copy:`One-week participation (MMFD-style breadth) is ${b5.toFixed(0)}%, meaning roughly ${b5.toFixed(0)} out of every 100 S&P 500 stocks are above their 5-day average.`,watch:'MMFD below 20% - fewer than 1 in 5 stocks above their 5-day average - would signal a washout developing. Back toward 50% would show buyers broadening out.',action:'Stay with the primary trend, but do not call this a bottoming setup yet.',role:'TACTICAL WEAKNESS'};
if(b5<50)return{stage:'Soft',tone:'neutral',headline:'Short-term participation is below normal',copy:`One-week participation (MMFD-style breadth) is ${b5.toFixed(0)}%, so fewer than half of S&P 500 stocks are above their 5-day average.`,watch:'MMFD-style participation above 50% would improve the read. A drop toward 20% would move the market toward a washout setup.',action:'Keep the primary trend as the anchor and watch whether participation repairs or deteriorates.',role:'TACTICAL SOFTNESS'};
return{stage:'Normal',tone:'constructive',headline:'No tactical washout is developing',copy:`One-week participation (MMFD-style breadth) is ${b5.toFixed(0)}%, meaning at least half of S&P 500 stocks are above their 5-day average.`,watch:'A sharp deterioration toward 20% - fewer than 1 in 5 stocks above their 5-day average - would materially change the tactical picture.',action:'Stay with the primary trend. There is no tactical extreme demanding a different posture.',role:'NO TACTICAL EXTREME'} }
function ensureHero(){const box=$('heroDecision');if(!box)return;box.classList.add('market-brief-grid');let meaning=box.children[0];let watch=box.children[box.children.length-1];if(meaning){meaning.classList.add('brief-meaning');const label=meaning.querySelector('span');if(label)label.textContent='WHAT THIS MEANS'}if(watch){watch.classList.add('brief-watch');const label=watch.querySelector('span');if(label)label.textContent='WATCH NEXT'}if(!$('heroTactical')){const card=document.createElement('div');card.id='heroTactical';card.className='hero-tactical-card';card.innerHTML='<span>TACTICAL SETUP</span><strong id="heroTacticalStage">—</strong><p id="heroTacticalWhy"></p><small id="heroTacticalRole"></small>';watch?box.insertBefore(card,watch):box.appendChild(card)}}
function ensureParticipation(){const mod=document.querySelector('.breadth-module');if(!mod||$('oneWeekParticipationCallout'))return;const head=mod.querySelector('.module-header');const x=document.createElement('article');x.id='oneWeekParticipationCallout';x.className='one-week-callout';x.innerHTML='<div><span>ONE-WEEK PARTICIPATION</span><small>Technical: MMFD-style breadth · % of S&P 500 stocks above their 5-day moving average</small></div><strong id="oneWeekValue">—</strong><p id="oneWeekRead"></p><details><summary>What is MMFD?</summary><p>MMFD-style breadth measures the percentage of S&P 500 stocks trading above their own 5-day moving average. A 20% reading means only 1 in 5 stocks is above that short-term trend. Very low readings show broad selling; a rebound from very low readings is often more useful because it shows buyers returning.</p></details>';head?.after(x)}
function compactHealth(){const sec=$('marketHealthGuide');if(!sec)return;sec.classList.add('compact-health');const h=sec.querySelector('.guide-heading h2');const p=sec.querySelector('.guide-heading>p');if(h)h.textContent='Three checks behind the market view';if(p)p.textContent='Trend sets the regime. Participation shows how many stocks are moving with it. Stress shows whether fear is confirming the move.'}
function simplifyNoChange(){const ch=$('strategistChanges');if(!ch)return;const no=ch.querySelector('.no-change');const sec=ch.closest('.intelligence-section');if(no&&sec){sec.classList.add('no-material-change');const title=sec.querySelector('.intelligence-heading h2');const p=sec.querySelector('.intelligence-heading p');if(title)title.textContent='No meaningful change since the prior close';if(p)p.textContent='The market thesis is unchanged. Routine daily noise is being filtered out.'}}
function labelHero(){const hero=document.querySelector('.premium-hero');if(!hero)return;const eye=hero.querySelector('.hero-grid .eyebrow');if(eye)eye.textContent='MARKET NOW';const cond=$('condition');if(cond&&!cond.previousElementSibling?.classList?.contains('regime-kicker')){const k=document.createElement('div');k.className='regime-kicker';k.textContent='PRIMARY REGIME';cond.before(k)}}
function render(d,h){const x=classify(d,h);ensureHero();ensureParticipation();compactHealth();simplifyNoChange();labelHero();const card=$('heroTactical');if(card)card.dataset.tone=x.tone;if($('heroTacticalStage'))$('heroTacticalStage').textContent=x.stage;if($('heroTacticalWhy'))$('heroTacticalWhy').textContent=`${x.headline}. ${x.copy}`;if($('heroTacticalRole'))$('heroTacticalRole').textContent=x.role;const meaning=document.querySelector('#heroDecision .brief-meaning');if(meaning){const strong=meaning.querySelector('strong'),p=meaning.querySelector('p');if(strong)strong.textContent=x.action.split('.')[0];if(p)p.textContent=x.action}const watch=document.querySelector('#heroDecision .brief-watch');if(watch){const strong=watch.querySelector('strong'),p=watch.querySelector('p');if(strong)strong.textContent=x.watch.split('.')[0];if(p)p.textContent=x.watch}const b5=num(d.breadth?.above_5d);if($('oneWeekValue'))$('oneWeekValue').textContent=b5==null?'—':`${b5.toFixed(0)}%`;if($('oneWeekRead'))$('oneWeekRead').textContent=`${x.headline}. ${x.watch}`;const tp=$('turningPointInternals');if(tp){const title=tp.querySelector('.guide-heading h2');if(title)title.textContent='Are we getting closer to a tradable turn?';const summary=$('tpText');if(summary)summary.textContent=`${x.copy} ${x.watch}`}}
async function boot(){try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!dr.ok)return;const d=await dr.json(),h=hr.ok?await hr.json():{};[200,700,1500,2800].forEach(ms=>setTimeout(()=>render(d,h),ms))}catch(e){console.warn('Tactical summary:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(boot,1000));
})();
