(()=>{
const $=id=>document.getElementById(id);
const num=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
function priorBreadth(history){const rows=(history?.breadth||[]).filter(x=>num(x?.above_5d)!=null);if(!rows.length)return{prev:null,min10:null};const vals=rows.map(x=>num(x.above_5d));return{prev:vals.length>1?vals[vals.length-2]:null,min10:Math.min(...vals.slice(-10))}}
function classify(d,h){const b=d.breadth||{},b5=num(b.above_5d),ad=num(b.ad_ratio),rsi=num(b.rsi_below_30),trin=num(b.trin),vix=num(d.vix?.value),{prev,min10}=priorBreadth(h);if(b5==null)return{stage:'Unavailable',tone:'neutral',headline:'Tactical participation data is unavailable',copy:'The primary market regime remains the guide until one-week participation is available.',watch:'Wait for a confirmed one-week participation reading.',role:'TACTICAL - DOES NOT OVERRIDE REGIME'};
const recover20=min10!=null&&min10<15&&prev!=null&&prev<=20&&b5>20;
const recover50=min10!=null&&min10<20&&prev!=null&&prev<=50&&b5>50;
const stressCount=[ad!=null&&ad<.7,rsi!=null&&rsi>=20,trin!=null&&trin>=1.3,vix!=null&&vix>=20].filter(Boolean).length;
if(recover50)return{stage:'Recovery confirming',tone:'constructive',headline:'Buyers are returning after broad weakness',copy:`One-week participation has rebounded to ${b5.toFixed(0)}% after falling below 20% recently. Recovery matters more than the oversold reading itself because participation is now broadening again.`,watch:'Look for the recovery to hold above 50% while intermediate support remains intact.',role:'CONFIRMATION'};
if(recover20)return{stage:'Stabilizing',tone:'constructive',headline:'The first recovery signal has appeared',copy:`One-week participation has recovered to ${b5.toFixed(0)}% after a sub-15% washout. That is early evidence that indiscriminate selling is easing, but it is not full confirmation yet.`,watch:'A move above 50% with stable intermediate support would strengthen the turn.',role:'EARLY RECOVERY'};
if(b5<10)return{stage:'Washout',tone:'stress',headline:'Selling is hitting almost everything',copy:`Only ${b5.toFixed(0)}% of S&P 500 stocks are above their one-week trend. This is an extreme tactical washout${stressCount?` with ${stressCount} other stress check${stressCount===1?'':'s'} also elevated`:''}. Extreme weakness raises rebound potential, but does not prove the low is in.`,watch:'The first useful improvement is one-week participation turning back above 20%, then 50%.',role:'TACTICAL EXTREME'};
if(b5<20)return{stage:'Washout developing',tone:'caution',headline:'Short-term selling is becoming extreme',copy:`Only ${b5.toFixed(0)}% of S&P 500 stocks are holding their one-week trend. Rebound potential is increasing, but buyers have not yet confirmed a turn.`,watch:'Watch for participation to stop falling and recover above 20% without intermediate support breaking.',role:'EXHAUSTION WATCH'};
if(b5<35)return{stage:'Weakening',tone:'caution',headline:'Selling is broad, but not yet a full washout',copy:`One-week participation is ${b5.toFixed(0)}%. Weakness is widespread enough to matter, but the evidence is not yet extreme enough to call capitulation.`,watch:'A drop below 20% would deepen the washout setup. A rebound toward 50% would show buyers returning.',role:'TACTICAL WEAKNESS'};
if(b5<50)return{stage:'Soft',tone:'neutral',headline:'Short-term participation is below normal',copy:`One-week participation is ${b5.toFixed(0)}%. The market is soft underneath the indexes, but this is not a tactical extreme.`,watch:'Watch whether participation recovers above 50% or deteriorates toward the 20% washout zone.',role:'TACTICAL SOFTNESS'};
return{stage:'Normal',tone:'constructive',headline:'No tactical washout is developing',copy:`One-week participation is ${b5.toFixed(0)}%, so short-term participation is broad enough that the market is not showing a washout signal.`,watch:'A sharp deterioration toward 20% would change the tactical picture.',role:'NO TACTICAL EXTREME'} }
function ensureHero(){const box=$('heroDecision');if(!box||$('heroTactical'))return;const watch=box.children[1];const card=document.createElement('div');card.id='heroTactical';card.className='hero-tactical-card';card.innerHTML='<span>TACTICAL SETUP</span><strong id="heroTacticalStage">—</strong><p id="heroTacticalWhy"></p><small id="heroTacticalRole"></small>';watch?box.insertBefore(card,watch):box.appendChild(card)}
function ensureParticipation(){const mod=document.querySelector('.breadth-module');if(!mod||$('oneWeekParticipationCallout'))return;const head=mod.querySelector('.module-header');const x=document.createElement('article');x.id='oneWeekParticipationCallout';x.className='one-week-callout';x.innerHTML='<div><span>ONE-WEEK PARTICIPATION</span><small>MMFD-style breadth · MMFD = percentage of S&P 500 stocks above their 5-day moving average</small></div><strong id="oneWeekValue">—</strong><p id="oneWeekRead"></p><details><summary>What is MMFD?</summary><p>MMFD is a short-term market-participation measure. It asks what percentage of S&P 500 stocks are trading above their own 5-day moving average. Very low readings mean selling is broad; a rebound from very low readings can be more useful than the extreme itself because it shows buyers returning.</p></details>';head?.after(x)}
function render(d,h){const x=classify(d,h);ensureHero();ensureParticipation();const card=$('heroTactical');if(card)card.dataset.tone=x.tone;if($('heroTacticalStage'))$('heroTacticalStage').textContent=x.stage;if($('heroTacticalWhy'))$('heroTacticalWhy').textContent=`${x.headline}. ${x.copy}`;if($('heroTacticalRole'))$('heroTacticalRole').textContent=x.role;const b5=num(d.breadth?.above_5d);if($('oneWeekValue'))$('oneWeekValue').textContent=b5==null?'—':`${b5.toFixed(0)}%`;if($('oneWeekRead'))$('oneWeekRead').textContent=`${x.headline}. ${x.watch}`;const tp=$('turningPointInternals');if(tp){const title=tp.querySelector('.guide-heading h2');if(title)title.textContent='Are we getting closer to a tradable turn?';const summary=$('tpText');if(summary)summary.textContent=`${x.copy} ${x.watch}`}}
async function boot(){try{const t=Date.now(),[dr,hr]=await Promise.all([fetch(`data/market_context.json?v=${t}`,{cache:'no-store'}),fetch(`data/history.json?v=${t}`,{cache:'no-store'})]);if(!dr.ok)return;const d=await dr.json(),h=hr.ok?await hr.json():{};[200,700,1500,2800].forEach(ms=>setTimeout(()=>render(d,h),ms))}catch(e){console.warn('Tactical summary:',e)}}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',boot);else boot();document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(boot,1000));
})();